//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACLInitParameters) DeepCopyInto(out *ACLInitParameters) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]UsersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACLInitParameters.
func (in *ACLInitParameters) DeepCopy() *ACLInitParameters {
	if in == nil {
		return nil
	}
	out := new(ACLInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACLObservation) DeepCopyInto(out *ACLObservation) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]UsersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACLObservation.
func (in *ACLObservation) DeepCopy() *ACLObservation {
	if in == nil {
		return nil
	}
	out := new(ACLObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACLParameters) DeepCopyInto(out *ACLParameters) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]UsersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACLParameters.
func (in *ACLParameters) DeepCopy() *ACLParameters {
	if in == nil {
		return nil
	}
	out := new(ACLParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoStopRequirementInitParameters) DeepCopyInto(out *AutoStopRequirementInitParameters) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Weeks != nil {
		in, out := &in.Weeks, &out.Weeks
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoStopRequirementInitParameters.
func (in *AutoStopRequirementInitParameters) DeepCopy() *AutoStopRequirementInitParameters {
	if in == nil {
		return nil
	}
	out := new(AutoStopRequirementInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoStopRequirementObservation) DeepCopyInto(out *AutoStopRequirementObservation) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Weeks != nil {
		in, out := &in.Weeks, &out.Weeks
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoStopRequirementObservation.
func (in *AutoStopRequirementObservation) DeepCopy() *AutoStopRequirementObservation {
	if in == nil {
		return nil
	}
	out := new(AutoStopRequirementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoStopRequirementParameters) DeepCopyInto(out *AutoStopRequirementParameters) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Weeks != nil {
		in, out := &in.Weeks, &out.Weeks
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoStopRequirementParameters.
func (in *AutoStopRequirementParameters) DeepCopy() *AutoStopRequirementParameters {
	if in == nil {
		return nil
	}
	out := new(AutoStopRequirementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupsInitParameters) DeepCopyInto(out *GroupsInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupsInitParameters.
func (in *GroupsInitParameters) DeepCopy() *GroupsInitParameters {
	if in == nil {
		return nil
	}
	out := new(GroupsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupsObservation) DeepCopyInto(out *GroupsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupsObservation.
func (in *GroupsObservation) DeepCopy() *GroupsObservation {
	if in == nil {
		return nil
	}
	out := new(GroupsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupsParameters) DeepCopyInto(out *GroupsParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupsParameters.
func (in *GroupsParameters) DeepCopy() *GroupsParameters {
	if in == nil {
		return nil
	}
	out := new(GroupsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerTagsInitParameters) DeepCopyInto(out *ProvisionerTagsInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerTagsInitParameters.
func (in *ProvisionerTagsInitParameters) DeepCopy() *ProvisionerTagsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProvisionerTagsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerTagsObservation) DeepCopyInto(out *ProvisionerTagsObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerTagsObservation.
func (in *ProvisionerTagsObservation) DeepCopy() *ProvisionerTagsObservation {
	if in == nil {
		return nil
	}
	out := new(ProvisionerTagsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerTagsParameters) DeepCopyInto(out *ProvisionerTagsParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerTagsParameters.
func (in *ProvisionerTagsParameters) DeepCopy() *ProvisionerTagsParameters {
	if in == nil {
		return nil
	}
	out := new(ProvisionerTagsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Template) DeepCopyInto(out *Template) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Template.
func (in *Template) DeepCopy() *Template {
	if in == nil {
		return nil
	}
	out := new(Template)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Template) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateInitParameters) DeepCopyInto(out *TemplateInitParameters) {
	*out = *in
	if in.ACL != nil {
		in, out := &in.ACL, &out.ACL
		*out = new(ACLInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ActivityBumpMs != nil {
		in, out := &in.ActivityBumpMs, &out.ActivityBumpMs
		*out = new(float64)
		**out = **in
	}
	if in.AgentsAllowed != nil {
		in, out := &in.AgentsAllowed, &out.AgentsAllowed
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserAutoStart != nil {
		in, out := &in.AllowUserAutoStart, &out.AllowUserAutoStart
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserAutoStop != nil {
		in, out := &in.AllowUserAutoStop, &out.AllowUserAutoStop
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserCancelWorkspaceJobs != nil {
		in, out := &in.AllowUserCancelWorkspaceJobs, &out.AllowUserCancelWorkspaceJobs
		*out = new(bool)
		**out = **in
	}
	if in.AutoStartPermittedDaysOfWeek != nil {
		in, out := &in.AutoStartPermittedDaysOfWeek, &out.AutoStartPermittedDaysOfWeek
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AutoStopRequirement != nil {
		in, out := &in.AutoStopRequirement, &out.AutoStopRequirement
		*out = new(AutoStopRequirementInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CorsBehavior != nil {
		in, out := &in.CorsBehavior, &out.CorsBehavior
		*out = new(string)
		**out = **in
	}
	if in.DefaultTTLMs != nil {
		in, out := &in.DefaultTTLMs, &out.DefaultTTLMs
		*out = new(float64)
		**out = **in
	}
	if in.DeprecationMessage != nil {
		in, out := &in.DeprecationMessage, &out.DeprecationMessage
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FailureTTLMs != nil {
		in, out := &in.FailureTTLMs, &out.FailureTTLMs
		*out = new(float64)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.MaxPortShareLevel != nil {
		in, out := &in.MaxPortShareLevel, &out.MaxPortShareLevel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireActiveVersion != nil {
		in, out := &in.RequireActiveVersion, &out.RequireActiveVersion
		*out = new(bool)
		**out = **in
	}
	if in.TimeTilDormantAutodeleteMs != nil {
		in, out := &in.TimeTilDormantAutodeleteMs, &out.TimeTilDormantAutodeleteMs
		*out = new(float64)
		**out = **in
	}
	if in.TimeTilDormantMs != nil {
		in, out := &in.TimeTilDormantMs, &out.TimeTilDormantMs
		*out = new(float64)
		**out = **in
	}
	if in.UseClassicParameterFlow != nil {
		in, out := &in.UseClassicParameterFlow, &out.UseClassicParameterFlow
		*out = new(bool)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]VersionsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateInitParameters.
func (in *TemplateInitParameters) DeepCopy() *TemplateInitParameters {
	if in == nil {
		return nil
	}
	out := new(TemplateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateList) DeepCopyInto(out *TemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Template, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateList.
func (in *TemplateList) DeepCopy() *TemplateList {
	if in == nil {
		return nil
	}
	out := new(TemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateObservation) DeepCopyInto(out *TemplateObservation) {
	*out = *in
	if in.ACL != nil {
		in, out := &in.ACL, &out.ACL
		*out = new(ACLObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ActivityBumpMs != nil {
		in, out := &in.ActivityBumpMs, &out.ActivityBumpMs
		*out = new(float64)
		**out = **in
	}
	if in.AgentsAllowed != nil {
		in, out := &in.AgentsAllowed, &out.AgentsAllowed
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserAutoStart != nil {
		in, out := &in.AllowUserAutoStart, &out.AllowUserAutoStart
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserAutoStop != nil {
		in, out := &in.AllowUserAutoStop, &out.AllowUserAutoStop
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserCancelWorkspaceJobs != nil {
		in, out := &in.AllowUserCancelWorkspaceJobs, &out.AllowUserCancelWorkspaceJobs
		*out = new(bool)
		**out = **in
	}
	if in.AutoStartPermittedDaysOfWeek != nil {
		in, out := &in.AutoStartPermittedDaysOfWeek, &out.AutoStartPermittedDaysOfWeek
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AutoStopRequirement != nil {
		in, out := &in.AutoStopRequirement, &out.AutoStopRequirement
		*out = new(AutoStopRequirementObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.CorsBehavior != nil {
		in, out := &in.CorsBehavior, &out.CorsBehavior
		*out = new(string)
		**out = **in
	}
	if in.DefaultTTLMs != nil {
		in, out := &in.DefaultTTLMs, &out.DefaultTTLMs
		*out = new(float64)
		**out = **in
	}
	if in.DeprecationMessage != nil {
		in, out := &in.DeprecationMessage, &out.DeprecationMessage
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FailureTTLMs != nil {
		in, out := &in.FailureTTLMs, &out.FailureTTLMs
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.MaxPortShareLevel != nil {
		in, out := &in.MaxPortShareLevel, &out.MaxPortShareLevel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.RequireActiveVersion != nil {
		in, out := &in.RequireActiveVersion, &out.RequireActiveVersion
		*out = new(bool)
		**out = **in
	}
	if in.TimeTilDormantAutodeleteMs != nil {
		in, out := &in.TimeTilDormantAutodeleteMs, &out.TimeTilDormantAutodeleteMs
		*out = new(float64)
		**out = **in
	}
	if in.TimeTilDormantMs != nil {
		in, out := &in.TimeTilDormantMs, &out.TimeTilDormantMs
		*out = new(float64)
		**out = **in
	}
	if in.UseClassicParameterFlow != nil {
		in, out := &in.UseClassicParameterFlow, &out.UseClassicParameterFlow
		*out = new(bool)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]VersionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateObservation.
func (in *TemplateObservation) DeepCopy() *TemplateObservation {
	if in == nil {
		return nil
	}
	out := new(TemplateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateParameters) DeepCopyInto(out *TemplateParameters) {
	*out = *in
	if in.ACL != nil {
		in, out := &in.ACL, &out.ACL
		*out = new(ACLParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ActivityBumpMs != nil {
		in, out := &in.ActivityBumpMs, &out.ActivityBumpMs
		*out = new(float64)
		**out = **in
	}
	if in.AgentsAllowed != nil {
		in, out := &in.AgentsAllowed, &out.AgentsAllowed
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserAutoStart != nil {
		in, out := &in.AllowUserAutoStart, &out.AllowUserAutoStart
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserAutoStop != nil {
		in, out := &in.AllowUserAutoStop, &out.AllowUserAutoStop
		*out = new(bool)
		**out = **in
	}
	if in.AllowUserCancelWorkspaceJobs != nil {
		in, out := &in.AllowUserCancelWorkspaceJobs, &out.AllowUserCancelWorkspaceJobs
		*out = new(bool)
		**out = **in
	}
	if in.AutoStartPermittedDaysOfWeek != nil {
		in, out := &in.AutoStartPermittedDaysOfWeek, &out.AutoStartPermittedDaysOfWeek
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AutoStopRequirement != nil {
		in, out := &in.AutoStopRequirement, &out.AutoStopRequirement
		*out = new(AutoStopRequirementParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CorsBehavior != nil {
		in, out := &in.CorsBehavior, &out.CorsBehavior
		*out = new(string)
		**out = **in
	}
	if in.DefaultTTLMs != nil {
		in, out := &in.DefaultTTLMs, &out.DefaultTTLMs
		*out = new(float64)
		**out = **in
	}
	if in.DeprecationMessage != nil {
		in, out := &in.DeprecationMessage, &out.DeprecationMessage
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FailureTTLMs != nil {
		in, out := &in.FailureTTLMs, &out.FailureTTLMs
		*out = new(float64)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.MaxPortShareLevel != nil {
		in, out := &in.MaxPortShareLevel, &out.MaxPortShareLevel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireActiveVersion != nil {
		in, out := &in.RequireActiveVersion, &out.RequireActiveVersion
		*out = new(bool)
		**out = **in
	}
	if in.TimeTilDormantAutodeleteMs != nil {
		in, out := &in.TimeTilDormantAutodeleteMs, &out.TimeTilDormantAutodeleteMs
		*out = new(float64)
		**out = **in
	}
	if in.TimeTilDormantMs != nil {
		in, out := &in.TimeTilDormantMs, &out.TimeTilDormantMs
		*out = new(float64)
		**out = **in
	}
	if in.UseClassicParameterFlow != nil {
		in, out := &in.UseClassicParameterFlow, &out.UseClassicParameterFlow
		*out = new(bool)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]VersionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateParameters.
func (in *TemplateParameters) DeepCopy() *TemplateParameters {
	if in == nil {
		return nil
	}
	out := new(TemplateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateSpec) DeepCopyInto(out *TemplateSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateSpec.
func (in *TemplateSpec) DeepCopy() *TemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateStatus) DeepCopyInto(out *TemplateStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateStatus.
func (in *TemplateStatus) DeepCopy() *TemplateStatus {
	if in == nil {
		return nil
	}
	out := new(TemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TfVarsInitParameters) DeepCopyInto(out *TfVarsInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TfVarsInitParameters.
func (in *TfVarsInitParameters) DeepCopy() *TfVarsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TfVarsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TfVarsObservation) DeepCopyInto(out *TfVarsObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TfVarsObservation.
func (in *TfVarsObservation) DeepCopy() *TfVarsObservation {
	if in == nil {
		return nil
	}
	out := new(TfVarsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TfVarsParameters) DeepCopyInto(out *TfVarsParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TfVarsParameters.
func (in *TfVarsParameters) DeepCopy() *TfVarsParameters {
	if in == nil {
		return nil
	}
	out := new(TfVarsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsersInitParameters) DeepCopyInto(out *UsersInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsersInitParameters.
func (in *UsersInitParameters) DeepCopy() *UsersInitParameters {
	if in == nil {
		return nil
	}
	out := new(UsersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsersObservation) DeepCopyInto(out *UsersObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsersObservation.
func (in *UsersObservation) DeepCopy() *UsersObservation {
	if in == nil {
		return nil
	}
	out := new(UsersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsersParameters) DeepCopyInto(out *UsersParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsersParameters.
func (in *UsersParameters) DeepCopy() *UsersParameters {
	if in == nil {
		return nil
	}
	out := new(UsersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionsInitParameters) DeepCopyInto(out *VersionsInitParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerTags != nil {
		in, out := &in.ProvisionerTags, &out.ProvisionerTags
		*out = make([]ProvisionerTagsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TfVars != nil {
		in, out := &in.TfVars, &out.TfVars
		*out = make([]TfVarsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionsInitParameters.
func (in *VersionsInitParameters) DeepCopy() *VersionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(VersionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionsObservation) DeepCopyInto(out *VersionsObservation) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
	if in.DirectoryHash != nil {
		in, out := &in.DirectoryHash, &out.DirectoryHash
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerTags != nil {
		in, out := &in.ProvisionerTags, &out.ProvisionerTags
		*out = make([]ProvisionerTagsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TfVars != nil {
		in, out := &in.TfVars, &out.TfVars
		*out = make([]TfVarsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionsObservation.
func (in *VersionsObservation) DeepCopy() *VersionsObservation {
	if in == nil {
		return nil
	}
	out := new(VersionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionsParameters) DeepCopyInto(out *VersionsParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerTags != nil {
		in, out := &in.ProvisionerTags, &out.ProvisionerTags
		*out = make([]ProvisionerTagsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TfVars != nil {
		in, out := &in.TfVars, &out.TfVars
		*out = make([]TfVarsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionsParameters.
func (in *VersionsParameters) DeepCopy() *VersionsParameters {
	if in == nil {
		return nil
	}
	out := new(VersionsParameters)
	in.DeepCopyInto(out)
	return out
}
