// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type GroupSyncInitParameters struct {

	// (Boolean) Controls whether groups will be created if they are missing.
	// Controls whether groups will be created if they are missing.
	AutoCreateMissing *bool `json:"autoCreateMissing,omitempty" tf:"auto_create_missing,omitempty"`

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what groups a user should be in.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder group ID.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`

	// (String) A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	RegexFilter *string `json:"regexFilter,omitempty" tf:"regex_filter,omitempty"`
}

type GroupSyncObservation struct {

	// (Boolean) Controls whether groups will be created if they are missing.
	// Controls whether groups will be created if they are missing.
	AutoCreateMissing *bool `json:"autoCreateMissing,omitempty" tf:"auto_create_missing,omitempty"`

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what groups a user should be in.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder group ID.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`

	// (String) A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	RegexFilter *string `json:"regexFilter,omitempty" tf:"regex_filter,omitempty"`
}

type GroupSyncParameters struct {

	// (Boolean) Controls whether groups will be created if they are missing.
	// Controls whether groups will be created if they are missing.
	// +kubebuilder:validation:Optional
	AutoCreateMissing *bool `json:"autoCreateMissing,omitempty" tf:"auto_create_missing,omitempty"`

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what groups a user should be in.
	// +kubebuilder:validation:Optional
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder group ID.
	// +kubebuilder:validation:Optional
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`

	// (String) A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// +kubebuilder:validation:Optional
	RegexFilter *string `json:"regexFilter,omitempty" tf:"regex_filter,omitempty"`
}

type OrganizationInitParameters struct {

	// in organization role names that are unioned into every member's effective roles. Changes propagate to members on their next request. Requires a Coder Deployment running v2.37.0 or later.
	// Built-in organization role names that are unioned into every member's effective roles. Changes propagate to members on their next request. Requires a Coder Deployment running v2.37.0 or later.
	// +listType=set
	DefaultOrgMemberRoles []*string `json:"defaultOrgMemberRoles,omitempty" tf:"default_org_member_roles,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Display name of the organization. Defaults to name.
	// Display name of the organization. Defaults to name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Block, Optional, Deprecated) Group sync settings to sync groups from an IdP.
	// Group sync settings to sync groups from an IdP.
	//
	// ~> **Deprecated** This block is deprecated. Use the `coderd_organization_group_sync` resource instead.
	GroupSync []GroupSyncInitParameters `json:"groupSync,omitempty" tf:"group_sync,omitempty"`

	// (String)
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the organization.
	// Name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Claims from the IdP provider that will give users access to this organization.
	// Claims from the IdP provider that will give users access to this organization.
	// +listType=set
	OrgSyncIdpGroups []*string `json:"orgSyncIdpGroups,omitempty" tf:"org_sync_idp_groups,omitempty"`

	// (Block, Optional) Role sync settings to sync organization roles from an IdP. (see below for nested schema)
	// Role sync settings to sync organization roles from an IdP.
	RoleSync []RoleSyncInitParameters `json:"roleSync,omitempty" tf:"role_sync,omitempty"`

	// (String) Workspace sharing setting for the organization. Valid values are everyone and none. Requires a Coder Deployment running v2.32.0 or later.
	// Workspace sharing setting for the organization. Valid values are `everyone` and `none`. Requires a Coder Deployment running v2.32.0 or later.
	WorkspaceSharing *string `json:"workspaceSharing,omitempty" tf:"workspace_sharing,omitempty"`
}

type OrganizationObservation struct {

	// in organization role names that are unioned into every member's effective roles. Changes propagate to members on their next request. Requires a Coder Deployment running v2.37.0 or later.
	// Built-in organization role names that are unioned into every member's effective roles. Changes propagate to members on their next request. Requires a Coder Deployment running v2.37.0 or later.
	// +listType=set
	DefaultOrgMemberRoles []*string `json:"defaultOrgMemberRoles,omitempty" tf:"default_org_member_roles,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Display name of the organization. Defaults to name.
	// Display name of the organization. Defaults to name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Block, Optional, Deprecated) Group sync settings to sync groups from an IdP.
	// Group sync settings to sync groups from an IdP.
	//
	// ~> **Deprecated** This block is deprecated. Use the `coderd_organization_group_sync` resource instead.
	GroupSync []GroupSyncObservation `json:"groupSync,omitempty" tf:"group_sync,omitempty"`

	// (String) Organization ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the organization.
	// Name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Claims from the IdP provider that will give users access to this organization.
	// Claims from the IdP provider that will give users access to this organization.
	// +listType=set
	OrgSyncIdpGroups []*string `json:"orgSyncIdpGroups,omitempty" tf:"org_sync_idp_groups,omitempty"`

	// (Block, Optional) Role sync settings to sync organization roles from an IdP. (see below for nested schema)
	// Role sync settings to sync organization roles from an IdP.
	RoleSync []RoleSyncObservation `json:"roleSync,omitempty" tf:"role_sync,omitempty"`

	// (String) Workspace sharing setting for the organization. Valid values are everyone and none. Requires a Coder Deployment running v2.32.0 or later.
	// Workspace sharing setting for the organization. Valid values are `everyone` and `none`. Requires a Coder Deployment running v2.32.0 or later.
	WorkspaceSharing *string `json:"workspaceSharing,omitempty" tf:"workspace_sharing,omitempty"`
}

type OrganizationParameters struct {

	// in organization role names that are unioned into every member's effective roles. Changes propagate to members on their next request. Requires a Coder Deployment running v2.37.0 or later.
	// Built-in organization role names that are unioned into every member's effective roles. Changes propagate to members on their next request. Requires a Coder Deployment running v2.37.0 or later.
	// +kubebuilder:validation:Optional
	// +listType=set
	DefaultOrgMemberRoles []*string `json:"defaultOrgMemberRoles,omitempty" tf:"default_org_member_roles,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Display name of the organization. Defaults to name.
	// Display name of the organization. Defaults to name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Block, Optional, Deprecated) Group sync settings to sync groups from an IdP.
	// Group sync settings to sync groups from an IdP.
	//
	// ~> **Deprecated** This block is deprecated. Use the `coderd_organization_group_sync` resource instead.
	// +kubebuilder:validation:Optional
	GroupSync []GroupSyncParameters `json:"groupSync,omitempty" tf:"group_sync,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the organization.
	// Name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Claims from the IdP provider that will give users access to this organization.
	// Claims from the IdP provider that will give users access to this organization.
	// +kubebuilder:validation:Optional
	// +listType=set
	OrgSyncIdpGroups []*string `json:"orgSyncIdpGroups,omitempty" tf:"org_sync_idp_groups,omitempty"`

	// (Block, Optional) Role sync settings to sync organization roles from an IdP. (see below for nested schema)
	// Role sync settings to sync organization roles from an IdP.
	// +kubebuilder:validation:Optional
	RoleSync []RoleSyncParameters `json:"roleSync,omitempty" tf:"role_sync,omitempty"`

	// (String) Workspace sharing setting for the organization. Valid values are everyone and none. Requires a Coder Deployment running v2.32.0 or later.
	// Workspace sharing setting for the organization. Valid values are `everyone` and `none`. Requires a Coder Deployment running v2.32.0 or later.
	// +kubebuilder:validation:Optional
	WorkspaceSharing *string `json:"workspaceSharing,omitempty" tf:"workspace_sharing,omitempty"`
}

type RoleSyncInitParameters struct {

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what organization roles a user should be given.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder organization role.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`
}

type RoleSyncObservation struct {

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what organization roles a user should be given.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder organization role.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`
}

type RoleSyncParameters struct {

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what organization roles a user should be given.
	// +kubebuilder:validation:Optional
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder organization role.
	// +kubebuilder:validation:Optional
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`
}

// OrganizationSpec defines the desired state of Organization
type OrganizationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationInitParameters `json:"initProvider,omitempty"`
}

// OrganizationStatus defines the observed state of Organization.
type OrganizationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Organization is the Schema for the Organizations API. An organization on the Coder deployment. ~> Warning This resource is only compatible with Coder version 2.16.0 https://github.com/coder/coder/releases/tag/v2.16.0 and later.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type Organization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationSpec   `json:"spec"`
	Status OrganizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationList contains a list of Organizations
type OrganizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Organization `json:"items"`
}

// Repository type metadata.
var (
	Organization_Kind             = "Organization"
	Organization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Organization_Kind}.String()
	Organization_KindAPIVersion   = Organization_Kind + "." + CRDGroupVersion.String()
	Organization_GroupVersionKind = CRDGroupVersion.WithKind(Organization_Kind)
)

func init() {
	SchemeBuilder.Register(&Organization{}, &OrganizationList{})
}
