// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type UserInitParameters struct {

	// (String) Email address of the user. Required unless is_service_account is true, in which case it must be omitted (service accounts have no email).
	// Email address of the user. Required unless `is_service_account` is `true`, in which case it must be omitted (service accounts have no email).
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// managed accounts that cannot log in interactively: they have no password or email and use login_type none. Unlike a regular login_type = none user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
	// Whether the user is a service account. Service accounts are admin-managed accounts that cannot log in interactively: they have no password or email and use `login_type` `none`. Unlike a regular `login_type = none` user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
	IsServiceAccount *bool `json:"isServiceAccount,omitempty" tf:"is_service_account,omitempty"`

	// (String) Type of login for the user. Valid types are none, password, github, and oidc.
	// Type of login for the user. Valid types are `none`, `password`, `github`, and `oidc`.
	LoginType *string `json:"loginType,omitempty" tf:"login_type,omitempty"`

	// (String) Display name of the user. Defaults to username.
	// Display name of the user. Defaults to username.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) Password for the user. Required when login_type is password. Passwords are saved into the state as plain text and should only be used for testing purposes.
	// Password for the user. Required when `login_type` is `password`. Passwords are saved into the state as plain text and should only be used for testing purposes.
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// admin, user-admin, and auditor. This attribute must be null if the user is an OIDC user and role sync is configured
	// Roles assigned to the user. Valid roles are `owner`, `template-admin`, `user-admin`, and `auditor`. This attribute must be null if the user is an OIDC user and role sync is configured
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Boolean) Whether the user is suspended.
	// Whether the user is suspended.
	Suspended *bool `json:"suspended,omitempty" tf:"suspended,omitempty"`

	// (String) Username of the user.
	// Username of the user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserObservation struct {

	// (String) Email address of the user. Required unless is_service_account is true, in which case it must be omitted (service accounts have no email).
	// Email address of the user. Required unless `is_service_account` is `true`, in which case it must be omitted (service accounts have no email).
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) User ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// managed accounts that cannot log in interactively: they have no password or email and use login_type none. Unlike a regular login_type = none user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
	// Whether the user is a service account. Service accounts are admin-managed accounts that cannot log in interactively: they have no password or email and use `login_type` `none`. Unlike a regular `login_type = none` user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
	IsServiceAccount *bool `json:"isServiceAccount,omitempty" tf:"is_service_account,omitempty"`

	// (String) Type of login for the user. Valid types are none, password, github, and oidc.
	// Type of login for the user. Valid types are `none`, `password`, `github`, and `oidc`.
	LoginType *string `json:"loginType,omitempty" tf:"login_type,omitempty"`

	// (String) Display name of the user. Defaults to username.
	// Display name of the user. Defaults to username.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// admin, user-admin, and auditor. This attribute must be null if the user is an OIDC user and role sync is configured
	// Roles assigned to the user. Valid roles are `owner`, `template-admin`, `user-admin`, and `auditor`. This attribute must be null if the user is an OIDC user and role sync is configured
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Boolean) Whether the user is suspended.
	// Whether the user is suspended.
	Suspended *bool `json:"suspended,omitempty" tf:"suspended,omitempty"`

	// (String) Username of the user.
	// Username of the user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserParameters struct {

	// (String) Email address of the user. Required unless is_service_account is true, in which case it must be omitted (service accounts have no email).
	// Email address of the user. Required unless `is_service_account` is `true`, in which case it must be omitted (service accounts have no email).
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// managed accounts that cannot log in interactively: they have no password or email and use login_type none. Unlike a regular login_type = none user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
	// Whether the user is a service account. Service accounts are admin-managed accounts that cannot log in interactively: they have no password or email and use `login_type` `none`. Unlike a regular `login_type = none` user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
	// +kubebuilder:validation:Optional
	IsServiceAccount *bool `json:"isServiceAccount,omitempty" tf:"is_service_account,omitempty"`

	// (String) Type of login for the user. Valid types are none, password, github, and oidc.
	// Type of login for the user. Valid types are `none`, `password`, `github`, and `oidc`.
	// +kubebuilder:validation:Optional
	LoginType *string `json:"loginType,omitempty" tf:"login_type,omitempty"`

	// (String) Display name of the user. Defaults to username.
	// Display name of the user. Defaults to username.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) Password for the user. Required when login_type is password. Passwords are saved into the state as plain text and should only be used for testing purposes.
	// Password for the user. Required when `login_type` is `password`. Passwords are saved into the state as plain text and should only be used for testing purposes.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// admin, user-admin, and auditor. This attribute must be null if the user is an OIDC user and role sync is configured
	// Roles assigned to the user. Valid roles are `owner`, `template-admin`, `user-admin`, and `auditor`. This attribute must be null if the user is an OIDC user and role sync is configured
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Boolean) Whether the user is suspended.
	// Whether the user is suspended.
	// +kubebuilder:validation:Optional
	Suspended *bool `json:"suspended,omitempty" tf:"suspended,omitempty"`

	// (String) Username of the user.
	// Username of the user.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. A user on the Coder deployment.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
