// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Organization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationGroupSync) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationSyncSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
