// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type GroupInitParameters struct {

	// (String) The URL of the group's avatar.
	// The URL of the group's avatar.
	AvatarURL *string `json:"avatarUrl,omitempty" tf:"avatar_url,omitempty"`

	// (String) The display name of the group. Defaults to the group name.
	// The display name of the group. Defaults to the group name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Set of String) Members of the group, by ID.coderd_group
	// Members of the group, by ID.coderd_group`
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.User
	// +listType=set
	Members []*string `json:"members,omitempty" tf:"members,omitempty"`

	// References to User in iam to populate members.
	// +kubebuilder:validation:Optional
	MembersRefs []v2.Reference `json:"membersRefs,omitempty" tf:"-"`

	// Selector for a list of User in iam to populate members.
	// +kubebuilder:validation:Optional
	MembersSelector *v2.Selector `json:"membersSelector,omitempty" tf:"-"`

	// (String) The unique name of the group.
	// The unique name of the group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID that the group belongs to. Defaults to the provider default organization ID.
	// The organization ID that the group belongs to. Defaults to the provider default organization ID.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.Reference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.Selector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (Number) The number of quota credits to allocate to each user in the group.
	// The number of quota credits to allocate to each user in the group.
	QuotaAllowance *float64 `json:"quotaAllowance,omitempty" tf:"quota_allowance,omitempty"`
}

type GroupObservation struct {

	// (String) The URL of the group's avatar.
	// The URL of the group's avatar.
	AvatarURL *string `json:"avatarUrl,omitempty" tf:"avatar_url,omitempty"`

	// (String) The display name of the group. Defaults to the group name.
	// The display name of the group. Defaults to the group name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) Group ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) Members of the group, by ID.coderd_group
	// Members of the group, by ID.coderd_group`
	// +listType=set
	Members []*string `json:"members,omitempty" tf:"members,omitempty"`

	// (String) The unique name of the group.
	// The unique name of the group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID that the group belongs to. Defaults to the provider default organization ID.
	// The organization ID that the group belongs to. Defaults to the provider default organization ID.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (Number) The number of quota credits to allocate to each user in the group.
	// The number of quota credits to allocate to each user in the group.
	QuotaAllowance *float64 `json:"quotaAllowance,omitempty" tf:"quota_allowance,omitempty"`
}

type GroupParameters struct {

	// (String) The URL of the group's avatar.
	// The URL of the group's avatar.
	// +kubebuilder:validation:Optional
	AvatarURL *string `json:"avatarUrl,omitempty" tf:"avatar_url,omitempty"`

	// (String) The display name of the group. Defaults to the group name.
	// The display name of the group. Defaults to the group name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Set of String) Members of the group, by ID.coderd_group
	// Members of the group, by ID.coderd_group`
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.User
	// +kubebuilder:validation:Optional
	// +listType=set
	Members []*string `json:"members,omitempty" tf:"members,omitempty"`

	// References to User in iam to populate members.
	// +kubebuilder:validation:Optional
	MembersRefs []v2.Reference `json:"membersRefs,omitempty" tf:"-"`

	// Selector for a list of User in iam to populate members.
	// +kubebuilder:validation:Optional
	MembersSelector *v2.Selector `json:"membersSelector,omitempty" tf:"-"`

	// (String) The unique name of the group.
	// The unique name of the group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID that the group belongs to. Defaults to the provider default organization ID.
	// The organization ID that the group belongs to. Defaults to the provider default organization ID.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.Reference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.Selector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (Number) The number of quota credits to allocate to each user in the group.
	// The number of quota credits to allocate to each user in the group.
	// +kubebuilder:validation:Optional
	QuotaAllowance *float64 `json:"quotaAllowance,omitempty" tf:"quota_allowance,omitempty"`
}

// GroupSpec defines the desired state of Group
type GroupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   GroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupInitParameters `json:"initProvider,omitempty"`
}

// GroupStatus defines the observed state of Group.
type GroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Group is the Schema for the Groups API. A group on the Coder deployment. Creating groups requires an Enterprise license.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coderd}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GroupSpec   `json:"spec"`
	Status GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Groups
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Repository type metadata.
var (
	Group_Kind             = "Group"
	Group_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Group_Kind}.String()
	Group_KindAPIVersion   = Group_Kind + "." + CRDGroupVersion.String()
	Group_GroupVersionKind = CRDGroupVersion.WithKind(Group_Kind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
