// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationGroupSyncInitParameters struct {

	// (Boolean) Controls whether groups will be created if they are missing. Defaults to false.
	// Controls whether groups will be created if they are missing. Defaults to false.
	AutoCreateMissing *bool `json:"autoCreateMissing,omitempty" tf:"auto_create_missing,omitempty"`

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what groups a user should be in.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder group ID.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`

	// (String) The ID of the organization to configure group sync for.
	// The ID of the organization to configure group sync for.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.Reference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.Selector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (String) A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	RegexFilter *string `json:"regexFilter,omitempty" tf:"regex_filter,omitempty"`
}

type OrganizationGroupSyncObservation struct {

	// (Boolean) Controls whether groups will be created if they are missing. Defaults to false.
	// Controls whether groups will be created if they are missing. Defaults to false.
	AutoCreateMissing *bool `json:"autoCreateMissing,omitempty" tf:"auto_create_missing,omitempty"`

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what groups a user should be in.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder group ID.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`

	// (String) The ID of the organization to configure group sync for.
	// The ID of the organization to configure group sync for.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	RegexFilter *string `json:"regexFilter,omitempty" tf:"regex_filter,omitempty"`
}

type OrganizationGroupSyncParameters struct {

	// (Boolean) Controls whether groups will be created if they are missing. Defaults to false.
	// Controls whether groups will be created if they are missing. Defaults to false.
	// +kubebuilder:validation:Optional
	AutoCreateMissing *bool `json:"autoCreateMissing,omitempty" tf:"auto_create_missing,omitempty"`

	// (String) The claim field that specifies what groups a user should be in.
	// The claim field that specifies what groups a user should be in.
	// +kubebuilder:validation:Optional
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder group ID.
	// A map from OIDC group name to Coder group ID.
	// +kubebuilder:validation:Optional
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`

	// (String) The ID of the organization to configure group sync for.
	// The ID of the organization to configure group sync for.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.Reference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.Selector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (String) A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
	// +kubebuilder:validation:Optional
	RegexFilter *string `json:"regexFilter,omitempty" tf:"regex_filter,omitempty"`
}

// OrganizationGroupSyncSpec defines the desired state of OrganizationGroupSync
type OrganizationGroupSyncSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrganizationGroupSyncParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationGroupSyncInitParameters `json:"initProvider,omitempty"`
}

// OrganizationGroupSyncStatus defines the observed state of OrganizationGroupSync.
type OrganizationGroupSyncStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationGroupSyncObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationGroupSync is the Schema for the OrganizationGroupSyncs API. Group sync settings for an organization on the Coder deployment. Multiple instances of this resource for a single organization will conflict. ~> Warning This resource is only compatible with Coder version 2.16.0 https://github.com/coder/coder/releases/tag/v2.16.0 and later.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coderd}
type OrganizationGroupSync struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.field) || (has(self.initProvider) && has(self.initProvider.field))",message="spec.forProvider.field is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mapping) || (has(self.initProvider) && has(self.initProvider.mapping))",message="spec.forProvider.mapping is a required parameter"
	Spec   OrganizationGroupSyncSpec   `json:"spec"`
	Status OrganizationGroupSyncStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationGroupSyncList contains a list of OrganizationGroupSyncs
type OrganizationGroupSyncList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationGroupSync `json:"items"`
}

// Repository type metadata.
var (
	OrganizationGroupSync_Kind             = "OrganizationGroupSync"
	OrganizationGroupSync_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationGroupSync_Kind}.String()
	OrganizationGroupSync_KindAPIVersion   = OrganizationGroupSync_Kind + "." + CRDGroupVersion.String()
	OrganizationGroupSync_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationGroupSync_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationGroupSync{}, &OrganizationGroupSyncList{})
}
