// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationSyncSettingsInitParameters struct {

	// (Boolean) When true, every user will be added to the default organization, regardless of claims.
	// When true, every user will be added to the default organization, regardless of claims.
	AssignDefault *bool `json:"assignDefault,omitempty" tf:"assign_default,omitempty"`

	// (String) The claim field that specifies what organizations a user should be in.
	// The claim field that specifies what organizations a user should be in.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder organization ID.
	// A map from OIDC group name to Coder organization ID.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`
}

type OrganizationSyncSettingsObservation struct {

	// (Boolean) When true, every user will be added to the default organization, regardless of claims.
	// When true, every user will be added to the default organization, regardless of claims.
	AssignDefault *bool `json:"assignDefault,omitempty" tf:"assign_default,omitempty"`

	// (String) The claim field that specifies what organizations a user should be in.
	// The claim field that specifies what organizations a user should be in.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder organization ID.
	// A map from OIDC group name to Coder organization ID.
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`
}

type OrganizationSyncSettingsParameters struct {

	// (Boolean) When true, every user will be added to the default organization, regardless of claims.
	// When true, every user will be added to the default organization, regardless of claims.
	// +kubebuilder:validation:Optional
	AssignDefault *bool `json:"assignDefault,omitempty" tf:"assign_default,omitempty"`

	// (String) The claim field that specifies what organizations a user should be in.
	// The claim field that specifies what organizations a user should be in.
	// +kubebuilder:validation:Optional
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// (Map of List of String) A map from OIDC group name to Coder organization ID.
	// A map from OIDC group name to Coder organization ID.
	// +kubebuilder:validation:Optional
	Mapping map[string][]*string `json:"mapping,omitempty" tf:"mapping,omitempty"`
}

// OrganizationSyncSettingsSpec defines the desired state of OrganizationSyncSettings
type OrganizationSyncSettingsSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrganizationSyncSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationSyncSettingsInitParameters `json:"initProvider,omitempty"`
}

// OrganizationSyncSettingsStatus defines the observed state of OrganizationSyncSettings.
type OrganizationSyncSettingsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationSyncSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationSyncSettings is the Schema for the OrganizationSyncSettingss API. IdP sync settings for organizations. This resource can only be created once. Attempts to create multiple will fail. ~> Warning This resource is only compatible with Coder version 2.19.0 https://github.com/coder/coder/releases/tag/v2.19.0 and later.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coderd}
type OrganizationSyncSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.assignDefault) || (has(self.initProvider) && has(self.initProvider.assignDefault))",message="spec.forProvider.assignDefault is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.field) || (has(self.initProvider) && has(self.initProvider.field))",message="spec.forProvider.field is a required parameter"
	Spec   OrganizationSyncSettingsSpec   `json:"spec"`
	Status OrganizationSyncSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationSyncSettingsList contains a list of OrganizationSyncSettingss
type OrganizationSyncSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationSyncSettings `json:"items"`
}

// Repository type metadata.
var (
	OrganizationSyncSettings_Kind             = "OrganizationSyncSettings"
	OrganizationSyncSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationSyncSettings_Kind}.String()
	OrganizationSyncSettings_KindAPIVersion   = OrganizationSyncSettings_Kind + "." + CRDGroupVersion.String()
	OrganizationSyncSettings_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationSyncSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationSyncSettings{}, &OrganizationSyncSettingsList{})
}
