// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AIProviderInitParameters struct {

	// only) Plaintext API key for the provider. Not valid for bedrock or copilot, or when settings.bedrock is set. Bump api_key_wo_version to rotate it.
	// Plaintext API key for the provider. Not valid for `bedrock` or `copilot`, or when `settings.bedrock` is set. Bump `api_key_wo_version` to rotate it.
	APIKeyWoSecretRef *v2.SecretKeySelector `json:"apiKeyWoSecretRef,omitempty" tf:"-"`

	// only API key. Required when api_key_wo is set; bump it whenever api_key_wo changes to rotate the stored key.
	// Version for the write-only API key. Required when `api_key_wo` is set; bump it whenever `api_key_wo` changes to rotate the stored key.
	APIKeyWoVersion *float64 `json:"apiKeyWoVersion,omitempty" tf:"api_key_wo_version,omitempty"`

	// (String) Absolute HTTP(S) base URL for the upstream provider endpoint.
	// Absolute HTTP(S) base URL for the upstream provider endpoint.
	BaseURL *string `json:"baseUrl,omitempty" tf:"base_url,omitempty"`

	// (String) Display name shown in Coder. If omitted, defaults to the provider name.
	// Display name shown in Coder. If omitted, defaults to the provider name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether this AI provider is enabled. Defaults to true.
	// Whether this AI provider is enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
	// Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// specific provider settings. (see below for nested schema)
	Settings *SettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// compat, openrouter, vercel, and copilot.
	// AI provider type. Valid values are `openai`, `anthropic`, `azure`, `bedrock`, `google`, `openai-compat`, `openrouter`, `vercel`, and `copilot`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AIProviderObservation struct {

	// (String) Masked API key value returned by Coder for display only.
	// Masked API key value returned by Coder for display only.
	APIKeyMasked *string `json:"apiKeyMasked,omitempty" tf:"api_key_masked,omitempty"`

	// only API key. Required when api_key_wo is set; bump it whenever api_key_wo changes to rotate the stored key.
	// Version for the write-only API key. Required when `api_key_wo` is set; bump it whenever `api_key_wo` changes to rotate the stored key.
	APIKeyWoVersion *float64 `json:"apiKeyWoVersion,omitempty" tf:"api_key_wo_version,omitempty"`

	// (String) Absolute HTTP(S) base URL for the upstream provider endpoint.
	// Absolute HTTP(S) base URL for the upstream provider endpoint.
	BaseURL *string `json:"baseUrl,omitempty" tf:"base_url,omitempty"`

	// (Number) Creation timestamp as Unix seconds.
	// Creation timestamp as Unix seconds.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Display name shown in Coder. If omitted, defaults to the provider name.
	// Display name shown in Coder. If omitted, defaults to the provider name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether this AI provider is enabled. Defaults to true.
	// Whether this AI provider is enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) AI provider ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
	// Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// specific provider settings. (see below for nested schema)
	Settings *SettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// compat, openrouter, vercel, and copilot.
	// AI provider type. Valid values are `openai`, `anthropic`, `azure`, `bedrock`, `google`, `openai-compat`, `openrouter`, `vercel`, and `copilot`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Number) Last update timestamp as Unix seconds.
	// Last update timestamp as Unix seconds.
	UpdatedAt *float64 `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type AIProviderParameters struct {

	// only) Plaintext API key for the provider. Not valid for bedrock or copilot, or when settings.bedrock is set. Bump api_key_wo_version to rotate it.
	// Plaintext API key for the provider. Not valid for `bedrock` or `copilot`, or when `settings.bedrock` is set. Bump `api_key_wo_version` to rotate it.
	// +kubebuilder:validation:Optional
	APIKeyWoSecretRef *v2.SecretKeySelector `json:"apiKeyWoSecretRef,omitempty" tf:"-"`

	// only API key. Required when api_key_wo is set; bump it whenever api_key_wo changes to rotate the stored key.
	// Version for the write-only API key. Required when `api_key_wo` is set; bump it whenever `api_key_wo` changes to rotate the stored key.
	// +kubebuilder:validation:Optional
	APIKeyWoVersion *float64 `json:"apiKeyWoVersion,omitempty" tf:"api_key_wo_version,omitempty"`

	// (String) Absolute HTTP(S) base URL for the upstream provider endpoint.
	// Absolute HTTP(S) base URL for the upstream provider endpoint.
	// +kubebuilder:validation:Optional
	BaseURL *string `json:"baseUrl,omitempty" tf:"base_url,omitempty"`

	// (String) Display name shown in Coder. If omitted, defaults to the provider name.
	// Display name shown in Coder. If omitted, defaults to the provider name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether this AI provider is enabled. Defaults to true.
	// Whether this AI provider is enabled. Defaults to true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
	// Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// specific provider settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Settings *SettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// compat, openrouter, vercel, and copilot.
	// AI provider type. Valid values are `openai`, `anthropic`, `azure`, `bedrock`, `google`, `openai-compat`, `openrouter`, `vercel`, and `copilot`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BedrockInitParameters struct {

	// only) AWS secret access key for Bedrock.
	// AWS secret access key for Bedrock.
	AccessKeySecretWoSecretRef *v2.SecretKeySelector `json:"accessKeySecretWoSecretRef,omitempty" tf:"-"`

	// only) AWS access key ID for Bedrock. See Coder's Amazon Bedrock provider docs.
	// AWS access key ID for Bedrock. See [Coder's Amazon Bedrock provider docs](https://coder.com/docs/ai-coder/ai-gateway/providers#amazon-bedrock).
	AccessKeyWoSecretRef *v2.SecretKeySelector `json:"accessKeyWoSecretRef,omitempty" tf:"-"`

	// only credentials. Bump this value to send, rotate, or clear credentials.
	// Version for Bedrock write-only credentials. Bump this value to send, rotate, or clear credentials.
	CredentialsWoVersion *float64 `json:"credentialsWoVersion,omitempty" tf:"credentials_wo_version,omitempty"`

	// (String) Primary Bedrock model identifier.
	// Primary Bedrock model identifier.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// model" (default) translates the native Messages request into Bedrock's InvokeModel format and requires model and small_fast_model. "mantle" forwards the native Messages request body unchanged with AWS SigV4 signing and passes through the client's model; requires region (the Mantle base URL is not a canonical Bedrock URL, so the region is never derived from base_url). Requires Coder v2.36.0 or later for the Mantle protocol. Omit (or set to "invoke-model") to use the default. Removing the attribute clears it back to the default; Coder maps an empty value to "invoke-model".
	// Bedrock wire protocol. `"invoke-model"` (default) translates the native Messages request into Bedrock's InvokeModel format and requires `model` and `small_fast_model`. `"mantle"` forwards the native Messages request body unchanged with AWS SigV4 signing and passes through the client's model; requires `region` (the Mantle base URL is not a canonical Bedrock URL, so the region is never derived from `base_url`). Requires Coder v2.36.0 or later for the Mantle protocol. Omit (or set to `"invoke-model"`) to use the default. Removing the attribute clears it back to the default; Coder maps an empty value to `"invoke-model"`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) AWS region for Bedrock. If omitted, derived from the canonical Bedrock base_url attribute.
	// AWS region for Bedrock. If omitted, derived from the canonical Bedrock `base_url` attribute.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) ARN of an AWS IAM role to assume via STS before calling Bedrock. The base identity (the AWS SDK default credential chain or the static credentials) signs the AssumeRole call, and the temporary credentials sign Bedrock requests. Omit to call Bedrock with the base identity directly. Requires Coder v2.35.0 or later.
	// ARN of an AWS IAM role to assume via STS before calling Bedrock. The base identity (the AWS SDK default credential chain or the static credentials) signs the AssumeRole call, and the temporary credentials sign Bedrock requests. Omit to call Bedrock with the base identity directly. Requires Coder v2.35.0 or later.
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// (String) Small/fast Bedrock model identifier used for background tasks.
	// Small/fast Bedrock model identifier used for background tasks.
	SmallFastModel *string `json:"smallFastModel,omitempty" tf:"small_fast_model,omitempty"`
}

type BedrockObservation struct {

	// only credentials. Bump this value to send, rotate, or clear credentials.
	// Version for Bedrock write-only credentials. Bump this value to send, rotate, or clear credentials.
	CredentialsWoVersion *float64 `json:"credentialsWoVersion,omitempty" tf:"credentials_wo_version,omitempty"`

	// (String) STS external ID the server generates and sends on the AssumeRole call when role_arn is set. Reference it in the assumed role's trust policy sts:ExternalId condition. Null until role_arn is first configured; stable afterwards. Requires Coder v2.36.0 or later.
	// STS external ID the server generates and sends on the AssumeRole call when `role_arn` is set. Reference it in the assumed role's trust policy `sts:ExternalId` condition. Null until `role_arn` is first configured; stable afterwards. Requires Coder v2.36.0 or later.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (String) Primary Bedrock model identifier.
	// Primary Bedrock model identifier.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// model" (default) translates the native Messages request into Bedrock's InvokeModel format and requires model and small_fast_model. "mantle" forwards the native Messages request body unchanged with AWS SigV4 signing and passes through the client's model; requires region (the Mantle base URL is not a canonical Bedrock URL, so the region is never derived from base_url). Requires Coder v2.36.0 or later for the Mantle protocol. Omit (or set to "invoke-model") to use the default. Removing the attribute clears it back to the default; Coder maps an empty value to "invoke-model".
	// Bedrock wire protocol. `"invoke-model"` (default) translates the native Messages request into Bedrock's InvokeModel format and requires `model` and `small_fast_model`. `"mantle"` forwards the native Messages request body unchanged with AWS SigV4 signing and passes through the client's model; requires `region` (the Mantle base URL is not a canonical Bedrock URL, so the region is never derived from `base_url`). Requires Coder v2.36.0 or later for the Mantle protocol. Omit (or set to `"invoke-model"`) to use the default. Removing the attribute clears it back to the default; Coder maps an empty value to `"invoke-model"`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) AWS region for Bedrock. If omitted, derived from the canonical Bedrock base_url attribute.
	// AWS region for Bedrock. If omitted, derived from the canonical Bedrock `base_url` attribute.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) ARN of an AWS IAM role to assume via STS before calling Bedrock. The base identity (the AWS SDK default credential chain or the static credentials) signs the AssumeRole call, and the temporary credentials sign Bedrock requests. Omit to call Bedrock with the base identity directly. Requires Coder v2.35.0 or later.
	// ARN of an AWS IAM role to assume via STS before calling Bedrock. The base identity (the AWS SDK default credential chain or the static credentials) signs the AssumeRole call, and the temporary credentials sign Bedrock requests. Omit to call Bedrock with the base identity directly. Requires Coder v2.35.0 or later.
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// (String) Small/fast Bedrock model identifier used for background tasks.
	// Small/fast Bedrock model identifier used for background tasks.
	SmallFastModel *string `json:"smallFastModel,omitempty" tf:"small_fast_model,omitempty"`
}

type BedrockParameters struct {

	// only) AWS secret access key for Bedrock.
	// AWS secret access key for Bedrock.
	// +kubebuilder:validation:Optional
	AccessKeySecretWoSecretRef *v2.SecretKeySelector `json:"accessKeySecretWoSecretRef,omitempty" tf:"-"`

	// only) AWS access key ID for Bedrock. See Coder's Amazon Bedrock provider docs.
	// AWS access key ID for Bedrock. See [Coder's Amazon Bedrock provider docs](https://coder.com/docs/ai-coder/ai-gateway/providers#amazon-bedrock).
	// +kubebuilder:validation:Optional
	AccessKeyWoSecretRef *v2.SecretKeySelector `json:"accessKeyWoSecretRef,omitempty" tf:"-"`

	// only credentials. Bump this value to send, rotate, or clear credentials.
	// Version for Bedrock write-only credentials. Bump this value to send, rotate, or clear credentials.
	// +kubebuilder:validation:Optional
	CredentialsWoVersion *float64 `json:"credentialsWoVersion,omitempty" tf:"credentials_wo_version,omitempty"`

	// (String) Primary Bedrock model identifier.
	// Primary Bedrock model identifier.
	// +kubebuilder:validation:Optional
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// model" (default) translates the native Messages request into Bedrock's InvokeModel format and requires model and small_fast_model. "mantle" forwards the native Messages request body unchanged with AWS SigV4 signing and passes through the client's model; requires region (the Mantle base URL is not a canonical Bedrock URL, so the region is never derived from base_url). Requires Coder v2.36.0 or later for the Mantle protocol. Omit (or set to "invoke-model") to use the default. Removing the attribute clears it back to the default; Coder maps an empty value to "invoke-model".
	// Bedrock wire protocol. `"invoke-model"` (default) translates the native Messages request into Bedrock's InvokeModel format and requires `model` and `small_fast_model`. `"mantle"` forwards the native Messages request body unchanged with AWS SigV4 signing and passes through the client's model; requires `region` (the Mantle base URL is not a canonical Bedrock URL, so the region is never derived from `base_url`). Requires Coder v2.36.0 or later for the Mantle protocol. Omit (or set to `"invoke-model"`) to use the default. Removing the attribute clears it back to the default; Coder maps an empty value to `"invoke-model"`.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) AWS region for Bedrock. If omitted, derived from the canonical Bedrock base_url attribute.
	// AWS region for Bedrock. If omitted, derived from the canonical Bedrock `base_url` attribute.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) ARN of an AWS IAM role to assume via STS before calling Bedrock. The base identity (the AWS SDK default credential chain or the static credentials) signs the AssumeRole call, and the temporary credentials sign Bedrock requests. Omit to call Bedrock with the base identity directly. Requires Coder v2.35.0 or later.
	// ARN of an AWS IAM role to assume via STS before calling Bedrock. The base identity (the AWS SDK default credential chain or the static credentials) signs the AssumeRole call, and the temporary credentials sign Bedrock requests. Omit to call Bedrock with the base identity directly. Requires Coder v2.35.0 or later.
	// +kubebuilder:validation:Optional
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// (String) Small/fast Bedrock model identifier used for background tasks.
	// Small/fast Bedrock model identifier used for background tasks.
	// +kubebuilder:validation:Optional
	SmallFastModel *string `json:"smallFastModel,omitempty" tf:"small_fast_model,omitempty"`
}

type SettingsInitParameters struct {

	// (Attributes) AWS Bedrock settings. Valid only for type = "bedrock" or type = "anthropic". (see below for nested schema)
	Bedrock *BedrockInitParameters `json:"bedrock,omitempty" tf:"bedrock,omitempty"`
}

type SettingsObservation struct {

	// (Attributes) AWS Bedrock settings. Valid only for type = "bedrock" or type = "anthropic". (see below for nested schema)
	Bedrock *BedrockObservation `json:"bedrock,omitempty" tf:"bedrock,omitempty"`
}

type SettingsParameters struct {

	// (Attributes) AWS Bedrock settings. Valid only for type = "bedrock" or type = "anthropic". (see below for nested schema)
	// +kubebuilder:validation:Optional
	Bedrock *BedrockParameters `json:"bedrock,omitempty" tf:"bedrock,omitempty"`
}

// AIProviderSpec defines the desired state of AIProvider
type AIProviderSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AIProviderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AIProviderInitParameters `json:"initProvider,omitempty"`
}

// AIProviderStatus defines the observed state of AIProvider.
type AIProviderStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AIProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AIProvider is the Schema for the AIProviders API. ~> This resource is experimental. Changes are expected, and it is not recommended for production use. -> _wo attributes are write-only https://developer.hashicorp.11 or later. Configures an AI Provider for use with Coder's AI Gateway & Coder Agents. For type = "bedrock", omit settings.bedrock.access_key_wo and settings.bedrock.access_key_secret_wo to use the AWS SDK default credential chain as resolved by the Coder server process (IAM role, IRSA, environment variables, shared config, SSO, IMDS, and more). Set both together to use static IAM-user credentials.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coderd}
type AIProvider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.baseUrl) || (has(self.initProvider) && has(self.initProvider.baseUrl))",message="spec.forProvider.baseUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   AIProviderSpec   `json:"spec"`
	Status AIProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AIProviderList contains a list of AIProviders
type AIProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIProvider `json:"items"`
}

// Repository type metadata.
var (
	AIProvider_Kind             = "AIProvider"
	AIProvider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AIProvider_Kind}.String()
	AIProvider_KindAPIVersion   = AIProvider_Kind + "." + CRDGroupVersion.String()
	AIProvider_GroupVersionKind = CRDGroupVersion.WithKind(AIProvider_Kind)
)

func init() {
	SchemeBuilder.Register(&AIProvider{}, &AIProviderList{})
}
