//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProvider) DeepCopyInto(out *AIProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProvider.
func (in *AIProvider) DeepCopy() *AIProvider {
	if in == nil {
		return nil
	}
	out := new(AIProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderInitParameters) DeepCopyInto(out *AIProviderInitParameters) {
	*out = *in
	if in.APIKeyWoSecretRef != nil {
		in, out := &in.APIKeyWoSecretRef, &out.APIKeyWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.APIKeyWoVersion != nil {
		in, out := &in.APIKeyWoVersion, &out.APIKeyWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.BaseURL != nil {
		in, out := &in.BaseURL, &out.BaseURL
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(SettingsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderInitParameters.
func (in *AIProviderInitParameters) DeepCopy() *AIProviderInitParameters {
	if in == nil {
		return nil
	}
	out := new(AIProviderInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderList) DeepCopyInto(out *AIProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderList.
func (in *AIProviderList) DeepCopy() *AIProviderList {
	if in == nil {
		return nil
	}
	out := new(AIProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderObservation) DeepCopyInto(out *AIProviderObservation) {
	*out = *in
	if in.APIKeyMasked != nil {
		in, out := &in.APIKeyMasked, &out.APIKeyMasked
		*out = new(string)
		**out = **in
	}
	if in.APIKeyWoVersion != nil {
		in, out := &in.APIKeyWoVersion, &out.APIKeyWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.BaseURL != nil {
		in, out := &in.BaseURL, &out.BaseURL
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(SettingsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderObservation.
func (in *AIProviderObservation) DeepCopy() *AIProviderObservation {
	if in == nil {
		return nil
	}
	out := new(AIProviderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderParameters) DeepCopyInto(out *AIProviderParameters) {
	*out = *in
	if in.APIKeyWoSecretRef != nil {
		in, out := &in.APIKeyWoSecretRef, &out.APIKeyWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.APIKeyWoVersion != nil {
		in, out := &in.APIKeyWoVersion, &out.APIKeyWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.BaseURL != nil {
		in, out := &in.BaseURL, &out.BaseURL
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(SettingsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderParameters.
func (in *AIProviderParameters) DeepCopy() *AIProviderParameters {
	if in == nil {
		return nil
	}
	out := new(AIProviderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderSpec) DeepCopyInto(out *AIProviderSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderSpec.
func (in *AIProviderSpec) DeepCopy() *AIProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AIProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderStatus) DeepCopyInto(out *AIProviderStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderStatus.
func (in *AIProviderStatus) DeepCopy() *AIProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AIProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockInitParameters) DeepCopyInto(out *BedrockInitParameters) {
	*out = *in
	if in.AccessKeySecretWoSecretRef != nil {
		in, out := &in.AccessKeySecretWoSecretRef, &out.AccessKeySecretWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.AccessKeyWoSecretRef != nil {
		in, out := &in.AccessKeyWoSecretRef, &out.AccessKeyWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.CredentialsWoVersion != nil {
		in, out := &in.CredentialsWoVersion, &out.CredentialsWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RoleArn != nil {
		in, out := &in.RoleArn, &out.RoleArn
		*out = new(string)
		**out = **in
	}
	if in.SmallFastModel != nil {
		in, out := &in.SmallFastModel, &out.SmallFastModel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockInitParameters.
func (in *BedrockInitParameters) DeepCopy() *BedrockInitParameters {
	if in == nil {
		return nil
	}
	out := new(BedrockInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockObservation) DeepCopyInto(out *BedrockObservation) {
	*out = *in
	if in.CredentialsWoVersion != nil {
		in, out := &in.CredentialsWoVersion, &out.CredentialsWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RoleArn != nil {
		in, out := &in.RoleArn, &out.RoleArn
		*out = new(string)
		**out = **in
	}
	if in.SmallFastModel != nil {
		in, out := &in.SmallFastModel, &out.SmallFastModel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockObservation.
func (in *BedrockObservation) DeepCopy() *BedrockObservation {
	if in == nil {
		return nil
	}
	out := new(BedrockObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockParameters) DeepCopyInto(out *BedrockParameters) {
	*out = *in
	if in.AccessKeySecretWoSecretRef != nil {
		in, out := &in.AccessKeySecretWoSecretRef, &out.AccessKeySecretWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.AccessKeyWoSecretRef != nil {
		in, out := &in.AccessKeyWoSecretRef, &out.AccessKeyWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.CredentialsWoVersion != nil {
		in, out := &in.CredentialsWoVersion, &out.CredentialsWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RoleArn != nil {
		in, out := &in.RoleArn, &out.RoleArn
		*out = new(string)
		**out = **in
	}
	if in.SmallFastModel != nil {
		in, out := &in.SmallFastModel, &out.SmallFastModel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockParameters.
func (in *BedrockParameters) DeepCopy() *BedrockParameters {
	if in == nil {
		return nil
	}
	out := new(BedrockParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModel) DeepCopyInto(out *DefaultModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModel.
func (in *DefaultModel) DeepCopy() *DefaultModel {
	if in == nil {
		return nil
	}
	out := new(DefaultModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModelInitParameters) DeepCopyInto(out *DefaultModelInitParameters) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
	if in.ModelIDRef != nil {
		in, out := &in.ModelIDRef, &out.ModelIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelIDSelector != nil {
		in, out := &in.ModelIDSelector, &out.ModelIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModelInitParameters.
func (in *DefaultModelInitParameters) DeepCopy() *DefaultModelInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultModelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModelList) DeepCopyInto(out *DefaultModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DefaultModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModelList.
func (in *DefaultModelList) DeepCopy() *DefaultModelList {
	if in == nil {
		return nil
	}
	out := new(DefaultModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModelObservation) DeepCopyInto(out *DefaultModelObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModelObservation.
func (in *DefaultModelObservation) DeepCopy() *DefaultModelObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultModelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModelParameters) DeepCopyInto(out *DefaultModelParameters) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
	if in.ModelIDRef != nil {
		in, out := &in.ModelIDRef, &out.ModelIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelIDSelector != nil {
		in, out := &in.ModelIDSelector, &out.ModelIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModelParameters.
func (in *DefaultModelParameters) DeepCopy() *DefaultModelParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultModelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModelSpec) DeepCopyInto(out *DefaultModelSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModelSpec.
func (in *DefaultModelSpec) DeepCopy() *DefaultModelSpec {
	if in == nil {
		return nil
	}
	out := new(DefaultModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModelStatus) DeepCopyInto(out *DefaultModelStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModelStatus.
func (in *DefaultModelStatus) DeepCopy() *DefaultModelStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServer) DeepCopyInto(out *MCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServer.
func (in *MCPServer) DeepCopy() *MCPServer {
	if in == nil {
		return nil
	}
	out := new(MCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerInitParameters) DeepCopyInto(out *MCPServerInitParameters) {
	*out = *in
	if in.APIKeyHeader != nil {
		in, out := &in.APIKeyHeader, &out.APIKeyHeader
		*out = new(string)
		**out = **in
	}
	if in.APIKeyValueWoSecretRef != nil {
		in, out := &in.APIKeyValueWoSecretRef, &out.APIKeyValueWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.APIKeyValueWoVersion != nil {
		in, out := &in.APIKeyValueWoVersion, &out.APIKeyValueWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.AllowInPlanMode != nil {
		in, out := &in.AllowInPlanMode, &out.AllowInPlanMode
		*out = new(bool)
		**out = **in
	}
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(string)
		**out = **in
	}
	if in.CustomHeadersWo != nil {
		in, out := &in.CustomHeadersWo, &out.CustomHeadersWo
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.CustomHeadersWoVersion != nil {
		in, out := &in.CustomHeadersWoVersion, &out.CustomHeadersWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ForwardCoderHeaders != nil {
		in, out := &in.ForwardCoderHeaders, &out.ForwardCoderHeaders
		*out = new(bool)
		**out = **in
	}
	if in.IconURL != nil {
		in, out := &in.IconURL, &out.IconURL
		*out = new(string)
		**out = **in
	}
	if in.ModelIntent != nil {
		in, out := &in.ModelIntent, &out.ModelIntent
		*out = new(bool)
		**out = **in
	}
	if in.Oauth2AuthURL != nil {
		in, out := &in.Oauth2AuthURL, &out.Oauth2AuthURL
		*out = new(string)
		**out = **in
	}
	if in.Oauth2ClientID != nil {
		in, out := &in.Oauth2ClientID, &out.Oauth2ClientID
		*out = new(string)
		**out = **in
	}
	if in.Oauth2ClientSecretWoSecretRef != nil {
		in, out := &in.Oauth2ClientSecretWoSecretRef, &out.Oauth2ClientSecretWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Oauth2ClientSecretWoVersion != nil {
		in, out := &in.Oauth2ClientSecretWoVersion, &out.Oauth2ClientSecretWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Oauth2RevocationURL != nil {
		in, out := &in.Oauth2RevocationURL, &out.Oauth2RevocationURL
		*out = new(string)
		**out = **in
	}
	if in.Oauth2Scopes != nil {
		in, out := &in.Oauth2Scopes, &out.Oauth2Scopes
		*out = new(string)
		**out = **in
	}
	if in.Oauth2TokenURL != nil {
		in, out := &in.Oauth2TokenURL, &out.Oauth2TokenURL
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.ToolAllowList != nil {
		in, out := &in.ToolAllowList, &out.ToolAllowList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ToolDenyList != nil {
		in, out := &in.ToolDenyList, &out.ToolDenyList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerInitParameters.
func (in *MCPServerInitParameters) DeepCopy() *MCPServerInitParameters {
	if in == nil {
		return nil
	}
	out := new(MCPServerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerList) DeepCopyInto(out *MCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerList.
func (in *MCPServerList) DeepCopy() *MCPServerList {
	if in == nil {
		return nil
	}
	out := new(MCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerObservation) DeepCopyInto(out *MCPServerObservation) {
	*out = *in
	if in.APIKeyHeader != nil {
		in, out := &in.APIKeyHeader, &out.APIKeyHeader
		*out = new(string)
		**out = **in
	}
	if in.APIKeyValueWoVersion != nil {
		in, out := &in.APIKeyValueWoVersion, &out.APIKeyValueWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.AllowInPlanMode != nil {
		in, out := &in.AllowInPlanMode, &out.AllowInPlanMode
		*out = new(bool)
		**out = **in
	}
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(float64)
		**out = **in
	}
	if in.CustomHeadersWoVersion != nil {
		in, out := &in.CustomHeadersWoVersion, &out.CustomHeadersWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ForwardCoderHeaders != nil {
		in, out := &in.ForwardCoderHeaders, &out.ForwardCoderHeaders
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IconURL != nil {
		in, out := &in.IconURL, &out.IconURL
		*out = new(string)
		**out = **in
	}
	if in.ModelIntent != nil {
		in, out := &in.ModelIntent, &out.ModelIntent
		*out = new(bool)
		**out = **in
	}
	if in.Oauth2AuthURL != nil {
		in, out := &in.Oauth2AuthURL, &out.Oauth2AuthURL
		*out = new(string)
		**out = **in
	}
	if in.Oauth2ClientID != nil {
		in, out := &in.Oauth2ClientID, &out.Oauth2ClientID
		*out = new(string)
		**out = **in
	}
	if in.Oauth2ClientSecretWoVersion != nil {
		in, out := &in.Oauth2ClientSecretWoVersion, &out.Oauth2ClientSecretWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Oauth2RevocationURL != nil {
		in, out := &in.Oauth2RevocationURL, &out.Oauth2RevocationURL
		*out = new(string)
		**out = **in
	}
	if in.Oauth2Scopes != nil {
		in, out := &in.Oauth2Scopes, &out.Oauth2Scopes
		*out = new(string)
		**out = **in
	}
	if in.Oauth2TokenURL != nil {
		in, out := &in.Oauth2TokenURL, &out.Oauth2TokenURL
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.ToolAllowList != nil {
		in, out := &in.ToolAllowList, &out.ToolAllowList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ToolDenyList != nil {
		in, out := &in.ToolDenyList, &out.ToolDenyList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerObservation.
func (in *MCPServerObservation) DeepCopy() *MCPServerObservation {
	if in == nil {
		return nil
	}
	out := new(MCPServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerParameters) DeepCopyInto(out *MCPServerParameters) {
	*out = *in
	if in.APIKeyHeader != nil {
		in, out := &in.APIKeyHeader, &out.APIKeyHeader
		*out = new(string)
		**out = **in
	}
	if in.APIKeyValueWoSecretRef != nil {
		in, out := &in.APIKeyValueWoSecretRef, &out.APIKeyValueWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.APIKeyValueWoVersion != nil {
		in, out := &in.APIKeyValueWoVersion, &out.APIKeyValueWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.AllowInPlanMode != nil {
		in, out := &in.AllowInPlanMode, &out.AllowInPlanMode
		*out = new(bool)
		**out = **in
	}
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(string)
		**out = **in
	}
	if in.CustomHeadersWoSecretRef != nil {
		in, out := &in.CustomHeadersWoSecretRef, &out.CustomHeadersWoSecretRef
		*out = new(v2.SecretReference)
		**out = **in
	}
	if in.CustomHeadersWoVersion != nil {
		in, out := &in.CustomHeadersWoVersion, &out.CustomHeadersWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ForwardCoderHeaders != nil {
		in, out := &in.ForwardCoderHeaders, &out.ForwardCoderHeaders
		*out = new(bool)
		**out = **in
	}
	if in.IconURL != nil {
		in, out := &in.IconURL, &out.IconURL
		*out = new(string)
		**out = **in
	}
	if in.ModelIntent != nil {
		in, out := &in.ModelIntent, &out.ModelIntent
		*out = new(bool)
		**out = **in
	}
	if in.Oauth2AuthURL != nil {
		in, out := &in.Oauth2AuthURL, &out.Oauth2AuthURL
		*out = new(string)
		**out = **in
	}
	if in.Oauth2ClientID != nil {
		in, out := &in.Oauth2ClientID, &out.Oauth2ClientID
		*out = new(string)
		**out = **in
	}
	if in.Oauth2ClientSecretWoSecretRef != nil {
		in, out := &in.Oauth2ClientSecretWoSecretRef, &out.Oauth2ClientSecretWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Oauth2ClientSecretWoVersion != nil {
		in, out := &in.Oauth2ClientSecretWoVersion, &out.Oauth2ClientSecretWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.Oauth2RevocationURL != nil {
		in, out := &in.Oauth2RevocationURL, &out.Oauth2RevocationURL
		*out = new(string)
		**out = **in
	}
	if in.Oauth2Scopes != nil {
		in, out := &in.Oauth2Scopes, &out.Oauth2Scopes
		*out = new(string)
		**out = **in
	}
	if in.Oauth2TokenURL != nil {
		in, out := &in.Oauth2TokenURL, &out.Oauth2TokenURL
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.ToolAllowList != nil {
		in, out := &in.ToolAllowList, &out.ToolAllowList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ToolDenyList != nil {
		in, out := &in.ToolDenyList, &out.ToolDenyList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerParameters.
func (in *MCPServerParameters) DeepCopy() *MCPServerParameters {
	if in == nil {
		return nil
	}
	out := new(MCPServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerStatus) DeepCopyInto(out *MCPServerStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerStatus.
func (in *MCPServerStatus) DeepCopy() *MCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelInitParameters) DeepCopyInto(out *ModelInitParameters) {
	*out = *in
	if in.AIProviderID != nil {
		in, out := &in.AIProviderID, &out.AIProviderID
		*out = new(string)
		**out = **in
	}
	if in.AIProviderIDRef != nil {
		in, out := &in.AIProviderIDRef, &out.AIProviderIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AIProviderIDSelector != nil {
		in, out := &in.AIProviderIDSelector, &out.AIProviderIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.CompressionThreshold != nil {
		in, out := &in.CompressionThreshold, &out.CompressionThreshold
		*out = new(float64)
		**out = **in
	}
	if in.ContextLimit != nil {
		in, out := &in.ContextLimit, &out.ContextLimit
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.ModelConfig != nil {
		in, out := &in.ModelConfig, &out.ModelConfig
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInitParameters.
func (in *ModelInitParameters) DeepCopy() *ModelInitParameters {
	if in == nil {
		return nil
	}
	out := new(ModelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelObservation) DeepCopyInto(out *ModelObservation) {
	*out = *in
	if in.AIProviderID != nil {
		in, out := &in.AIProviderID, &out.AIProviderID
		*out = new(string)
		**out = **in
	}
	if in.CompressionThreshold != nil {
		in, out := &in.CompressionThreshold, &out.CompressionThreshold
		*out = new(float64)
		**out = **in
	}
	if in.ContextLimit != nil {
		in, out := &in.ContextLimit, &out.ContextLimit
		*out = new(float64)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.ModelConfig != nil {
		in, out := &in.ModelConfig, &out.ModelConfig
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelObservation.
func (in *ModelObservation) DeepCopy() *ModelObservation {
	if in == nil {
		return nil
	}
	out := new(ModelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelParameters) DeepCopyInto(out *ModelParameters) {
	*out = *in
	if in.AIProviderID != nil {
		in, out := &in.AIProviderID, &out.AIProviderID
		*out = new(string)
		**out = **in
	}
	if in.AIProviderIDRef != nil {
		in, out := &in.AIProviderIDRef, &out.AIProviderIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AIProviderIDSelector != nil {
		in, out := &in.AIProviderIDSelector, &out.AIProviderIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.CompressionThreshold != nil {
		in, out := &in.CompressionThreshold, &out.CompressionThreshold
		*out = new(float64)
		**out = **in
	}
	if in.ContextLimit != nil {
		in, out := &in.ContextLimit, &out.ContextLimit
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.ModelConfig != nil {
		in, out := &in.ModelConfig, &out.ModelConfig
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.OrganizationIDRef != nil {
		in, out := &in.OrganizationIDRef, &out.OrganizationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationIDSelector != nil {
		in, out := &in.OrganizationIDSelector, &out.OrganizationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelParameters.
func (in *ModelParameters) DeepCopy() *ModelParameters {
	if in == nil {
		return nil
	}
	out := new(ModelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsInitParameters) DeepCopyInto(out *SettingsInitParameters) {
	*out = *in
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsInitParameters.
func (in *SettingsInitParameters) DeepCopy() *SettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsObservation) DeepCopyInto(out *SettingsObservation) {
	*out = *in
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsObservation.
func (in *SettingsObservation) DeepCopy() *SettingsObservation {
	if in == nil {
		return nil
	}
	out := new(SettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsParameters) DeepCopyInto(out *SettingsParameters) {
	*out = *in
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsParameters.
func (in *SettingsParameters) DeepCopy() *SettingsParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPrompt) DeepCopyInto(out *SystemPrompt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPrompt.
func (in *SystemPrompt) DeepCopy() *SystemPrompt {
	if in == nil {
		return nil
	}
	out := new(SystemPrompt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemPrompt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptInitParameters) DeepCopyInto(out *SystemPromptInitParameters) {
	*out = *in
	if in.IncludeDefaultSystemPrompt != nil {
		in, out := &in.IncludeDefaultSystemPrompt, &out.IncludeDefaultSystemPrompt
		*out = new(bool)
		**out = **in
	}
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptInitParameters.
func (in *SystemPromptInitParameters) DeepCopy() *SystemPromptInitParameters {
	if in == nil {
		return nil
	}
	out := new(SystemPromptInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptList) DeepCopyInto(out *SystemPromptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemPrompt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptList.
func (in *SystemPromptList) DeepCopy() *SystemPromptList {
	if in == nil {
		return nil
	}
	out := new(SystemPromptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemPromptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptObservation) DeepCopyInto(out *SystemPromptObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncludeDefaultSystemPrompt != nil {
		in, out := &in.IncludeDefaultSystemPrompt, &out.IncludeDefaultSystemPrompt
		*out = new(bool)
		**out = **in
	}
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptObservation.
func (in *SystemPromptObservation) DeepCopy() *SystemPromptObservation {
	if in == nil {
		return nil
	}
	out := new(SystemPromptObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptParameters) DeepCopyInto(out *SystemPromptParameters) {
	*out = *in
	if in.IncludeDefaultSystemPrompt != nil {
		in, out := &in.IncludeDefaultSystemPrompt, &out.IncludeDefaultSystemPrompt
		*out = new(bool)
		**out = **in
	}
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptParameters.
func (in *SystemPromptParameters) DeepCopy() *SystemPromptParameters {
	if in == nil {
		return nil
	}
	out := new(SystemPromptParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptSpec) DeepCopyInto(out *SystemPromptSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptSpec.
func (in *SystemPromptSpec) DeepCopy() *SystemPromptSpec {
	if in == nil {
		return nil
	}
	out := new(SystemPromptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptStatus) DeepCopyInto(out *SystemPromptStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptStatus.
func (in *SystemPromptStatus) DeepCopy() *SystemPromptStatus {
	if in == nil {
		return nil
	}
	out := new(SystemPromptStatus)
	in.DeepCopyInto(out)
	return out
}
