// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SystemPromptInitParameters struct {

	// in system prompt (true, the default) or replaces it entirely (false).
	// Whether the custom prompt is appended to Coder's built-in system prompt (`true`, the default) or replaces it entirely (`false`).
	IncludeDefaultSystemPrompt *bool `json:"includeDefaultSystemPrompt,omitempty" tf:"include_default_system_prompt,omitempty"`

	// prompt.md"). Limited to 128 KiB after sanitization.
	// The custom system prompt text, typically `file("${path.module}/system-prompt.md")`. Limited to 128 KiB after sanitization.
	SystemPrompt *string `json:"systemPrompt,omitempty" tf:"system_prompt,omitempty"`
}

type SystemPromptObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// in system prompt (true, the default) or replaces it entirely (false).
	// Whether the custom prompt is appended to Coder's built-in system prompt (`true`, the default) or replaces it entirely (`false`).
	IncludeDefaultSystemPrompt *bool `json:"includeDefaultSystemPrompt,omitempty" tf:"include_default_system_prompt,omitempty"`

	// prompt.md"). Limited to 128 KiB after sanitization.
	// The custom system prompt text, typically `file("${path.module}/system-prompt.md")`. Limited to 128 KiB after sanitization.
	SystemPrompt *string `json:"systemPrompt,omitempty" tf:"system_prompt,omitempty"`
}

type SystemPromptParameters struct {

	// in system prompt (true, the default) or replaces it entirely (false).
	// Whether the custom prompt is appended to Coder's built-in system prompt (`true`, the default) or replaces it entirely (`false`).
	// +kubebuilder:validation:Optional
	IncludeDefaultSystemPrompt *bool `json:"includeDefaultSystemPrompt,omitempty" tf:"include_default_system_prompt,omitempty"`

	// prompt.md"). Limited to 128 KiB after sanitization.
	// The custom system prompt text, typically `file("${path.module}/system-prompt.md")`. Limited to 128 KiB after sanitization.
	// +kubebuilder:validation:Optional
	SystemPrompt *string `json:"systemPrompt,omitempty" tf:"system_prompt,omitempty"`
}

// SystemPromptSpec defines the desired state of SystemPrompt
type SystemPromptSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SystemPromptParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SystemPromptInitParameters `json:"initProvider,omitempty"`
}

// SystemPromptStatus defines the observed state of SystemPrompt.
type SystemPromptStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SystemPromptObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SystemPrompt is the Schema for the SystemPrompts API. ~> This resource is experimental. Changes are to be expected, and we recommend using it with caution in production environments. The deployment-wide chat system prompt for Coder Agents (Settings → Instructions in the dashboard). This is a deployment-wide singleton. Declare it once; duplicate resources silently overwrite each other. Coder sanitizes the stored prompt (strips invisible Unicode characters, normalizes line endings, collapses runs of blank lines, and trims surrounding whitespace), and this resource compares values the same way, so a trailing newline from file(...) does not cause drift after apply. On the first plan after an import, a configured value that differs from the live one only by sanitization shows a single in-place normalization update and then converges; use trimspace(file(...)) to avoid even that. The API has no delete operation for this setting. ~> Warning This resource requires Coder version 2.37.0 https://github.com/coder/coder/releases/tag/v2.37.0 or later, and a token with site-wide owner permissions.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coderd}
type SystemPrompt struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.systemPrompt) || (has(self.initProvider) && has(self.initProvider.systemPrompt))",message="spec.forProvider.systemPrompt is a required parameter"
	Spec   SystemPromptSpec   `json:"spec"`
	Status SystemPromptStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SystemPromptList contains a list of SystemPrompts
type SystemPromptList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SystemPrompt `json:"items"`
}

// Repository type metadata.
var (
	SystemPrompt_Kind             = "SystemPrompt"
	SystemPrompt_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SystemPrompt_Kind}.String()
	SystemPrompt_KindAPIVersion   = SystemPrompt_Kind + "." + CRDGroupVersion.String()
	SystemPrompt_GroupVersionKind = CRDGroupVersion.WithKind(SystemPrompt_Kind)
)

func init() {
	SchemeBuilder.Register(&SystemPrompt{}, &SystemPromptList{})
}
