// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *License) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OAuth2ProviderSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProvisionerKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceProxy) Hub() {}
