// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type LicenseInitParameters struct {

	// (String, Sensitive) A license key for Coder.
	// A license key for Coder.
	LicenseSecretRef v2.LocalSecretKeySelector `json:"licenseSecretRef" tf:"-"`
}

type LicenseObservation struct {

	// (Number) Unix timestamp of when the license expires.
	// Unix timestamp of when the license expires.
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (Number) Integer ID of the license.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type LicenseParameters struct {

	// (String, Sensitive) A license key for Coder.
	// A license key for Coder.
	// +kubebuilder:validation:Optional
	LicenseSecretRef v2.LocalSecretKeySelector `json:"licenseSecretRef" tf:"-"`
}

// LicenseSpec defines the desired state of License
type LicenseSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LicenseParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LicenseInitParameters `json:"initProvider,omitempty"`
}

// LicenseStatus defines the observed state of License.
type LicenseStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               LicenseObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// License is the Schema for the Licenses API. A license for a Coder deployment. It's recommended to set create_before_destroy https://developer.hashicorp. This will result in a temporary disruption to your users; during which they may be unable to use features that require a license. The depends_on meta-argument is instead recommended.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type License struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.licenseSecretRef)",message="spec.forProvider.licenseSecretRef is a required parameter"
	Spec   LicenseSpec   `json:"spec"`
	Status LicenseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LicenseList contains a list of Licenses
type LicenseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []License `json:"items"`
}

// Repository type metadata.
var (
	License_Kind             = "License"
	License_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: License_Kind}.String()
	License_KindAPIVersion   = License_Kind + "." + CRDGroupVersion.String()
	License_GroupVersionKind = CRDGroupVersion.WithKind(License_Kind)
)

func init() {
	SchemeBuilder.Register(&License{}, &LicenseList{})
}
