// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OAuth2ProviderSettingsInitParameters struct {

	// (Boolean) Whether OAuth2 Dynamic Client Registration (RFC 7591) is enabled for the deployment. When disabled, POST /oauth2/register is rejected and the registration_endpoint is omitted from the authorization server metadata document.
	// Whether OAuth2 Dynamic Client Registration ([RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)) is enabled for the deployment. When disabled, `POST /oauth2/register` is rejected and the `registration_endpoint` is omitted from the authorization server metadata document.
	DynamicClientRegistrationEnabled *bool `json:"dynamicClientRegistrationEnabled,omitempty" tf:"dynamic_client_registration_enabled,omitempty"`
}

type OAuth2ProviderSettingsObservation struct {

	// (Boolean) Whether OAuth2 Dynamic Client Registration (RFC 7591) is enabled for the deployment. When disabled, POST /oauth2/register is rejected and the registration_endpoint is omitted from the authorization server metadata document.
	// Whether OAuth2 Dynamic Client Registration ([RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)) is enabled for the deployment. When disabled, `POST /oauth2/register` is rejected and the `registration_endpoint` is omitted from the authorization server metadata document.
	DynamicClientRegistrationEnabled *bool `json:"dynamicClientRegistrationEnabled,omitempty" tf:"dynamic_client_registration_enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type OAuth2ProviderSettingsParameters struct {

	// (Boolean) Whether OAuth2 Dynamic Client Registration (RFC 7591) is enabled for the deployment. When disabled, POST /oauth2/register is rejected and the registration_endpoint is omitted from the authorization server metadata document.
	// Whether OAuth2 Dynamic Client Registration ([RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)) is enabled for the deployment. When disabled, `POST /oauth2/register` is rejected and the `registration_endpoint` is omitted from the authorization server metadata document.
	// +kubebuilder:validation:Optional
	DynamicClientRegistrationEnabled *bool `json:"dynamicClientRegistrationEnabled,omitempty" tf:"dynamic_client_registration_enabled,omitempty"`
}

// OAuth2ProviderSettingsSpec defines the desired state of OAuth2ProviderSettings
type OAuth2ProviderSettingsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OAuth2ProviderSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OAuth2ProviderSettingsInitParameters `json:"initProvider,omitempty"`
}

// OAuth2ProviderSettingsStatus defines the observed state of OAuth2ProviderSettings.
type OAuth2ProviderSettingsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OAuth2ProviderSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OAuth2ProviderSettings is the Schema for the OAuth2ProviderSettingss API. Deployment-wide OAuth2 provider settings. This is a deployment-wide singleton. Declare it once; duplicate resources silently overwrite each other. The API has no delete operation for this setting, so the value cannot be returned to a "never configured" state. -> Omit this resource to leave DCR unmanaged. ~> Warning This resource is only compatible with Coder version 2.37.0 https://github.com/coder/coder/releases/tag/v2.37.0 and later. ~> Warning Requires the oauth2 experiment (CODER_EXPERIMENTS=oauth2 or --experiments=oauth2); * does not enable it. Without it, /api/v2/oauth2-provider/settings returns 403 (development builds bypass this check).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type OAuth2ProviderSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dynamicClientRegistrationEnabled) || (has(self.initProvider) && has(self.initProvider.dynamicClientRegistrationEnabled))",message="spec.forProvider.dynamicClientRegistrationEnabled is a required parameter"
	Spec   OAuth2ProviderSettingsSpec   `json:"spec"`
	Status OAuth2ProviderSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OAuth2ProviderSettingsList contains a list of OAuth2ProviderSettingss
type OAuth2ProviderSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OAuth2ProviderSettings `json:"items"`
}

// Repository type metadata.
var (
	OAuth2ProviderSettings_Kind             = "OAuth2ProviderSettings"
	OAuth2ProviderSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OAuth2ProviderSettings_Kind}.String()
	OAuth2ProviderSettings_KindAPIVersion   = OAuth2ProviderSettings_Kind + "." + CRDGroupVersion.String()
	OAuth2ProviderSettings_GroupVersionKind = CRDGroupVersion.WithKind(OAuth2ProviderSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&OAuth2ProviderSettings{}, &OAuth2ProviderSettingsList{})
}
