// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WorkspaceProxyInitParameters struct {

	// (String) Display name of the workspace proxy.
	// Display name of the workspace proxy.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// Relative path or external URL that specifies an icon to be displayed in the dashboard.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the workspace proxy.
	// Name of the workspace proxy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type WorkspaceProxyObservation struct {

	// (String) Display name of the workspace proxy.
	// Display name of the workspace proxy.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) Workspace Proxy ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// Relative path or external URL that specifies an icon to be displayed in the dashboard.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the workspace proxy.
	// Name of the workspace proxy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type WorkspaceProxyParameters struct {

	// (String) Display name of the workspace proxy.
	// Display name of the workspace proxy.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// +kubebuilder:validation:Optional
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the workspace proxy.
	// Name of the workspace proxy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// WorkspaceProxySpec defines the desired state of WorkspaceProxy
type WorkspaceProxySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WorkspaceProxyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceProxyInitParameters `json:"initProvider,omitempty"`
}

// WorkspaceProxyStatus defines the observed state of WorkspaceProxy.
type WorkspaceProxyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WorkspaceProxyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceProxy is the Schema for the WorkspaceProxys API. A Workspace Proxy for the Coder deployment.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type WorkspaceProxy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.icon) || (has(self.initProvider) && has(self.initProvider.icon))",message="spec.forProvider.icon is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   WorkspaceProxySpec   `json:"spec"`
	Status WorkspaceProxyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceProxyList contains a list of WorkspaceProxys
type WorkspaceProxyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceProxy `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceProxy_Kind             = "WorkspaceProxy"
	WorkspaceProxy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceProxy_Kind}.String()
	WorkspaceProxy_KindAPIVersion   = WorkspaceProxy_Kind + "." + CRDGroupVersion.String()
	WorkspaceProxy_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceProxy_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceProxy{}, &WorkspaceProxyList{})
}
