// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DefaultModelInitParameters struct {

	// (String) ID of the coderd_agents_model to mark as the organization's default. Usually this is coderd_agents_model.<name>.id.
	// ID of the `coderd_agents_model` to mark as the organization's default. Usually this is `coderd_agents_model.<name>.id`.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/agents/v1alpha1.Model
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in agents to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v2.NamespacedReference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in agents to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v2.NamespacedSelector `json:"modelIdSelector,omitempty" tf:"-"`

	// (String) Organization ID whose default Agents model is managed.
	// Organization ID whose default Agents model is managed.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`
}

type DefaultModelObservation struct {

	// (String) Organization ID that identifies this organization's default Agents model selection.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the coderd_agents_model to mark as the organization's default. Usually this is coderd_agents_model.<name>.id.
	// ID of the `coderd_agents_model` to mark as the organization's default. Usually this is `coderd_agents_model.<name>.id`.
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// (String) Organization ID whose default Agents model is managed.
	// Organization ID whose default Agents model is managed.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type DefaultModelParameters struct {

	// (String) ID of the coderd_agents_model to mark as the organization's default. Usually this is coderd_agents_model.<name>.id.
	// ID of the `coderd_agents_model` to mark as the organization's default. Usually this is `coderd_agents_model.<name>.id`.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/agents/v1alpha1.Model
	// +kubebuilder:validation:Optional
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in agents to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v2.NamespacedReference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in agents to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v2.NamespacedSelector `json:"modelIdSelector,omitempty" tf:"-"`

	// (String) Organization ID whose default Agents model is managed.
	// Organization ID whose default Agents model is managed.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`
}

// DefaultModelSpec defines the desired state of DefaultModel
type DefaultModelSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DefaultModelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DefaultModelInitParameters `json:"initProvider,omitempty"`
}

// DefaultModelStatus defines the observed state of DefaultModel.
type DefaultModelStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DefaultModelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DefaultModel is the Schema for the DefaultModels API. ~> This resource is experimental. Changes are expected, and it is not recommended for production use. ~> Warning This resource is only compatible with Coder version 2.37.0 https://github.com/coder/coder/releases/tag/v2.37.0 and later. Selects which coderd_agents_model is the default chat model for Coder Agents in an organization. Coder enforces a single default model per organization: marking a model as default automatically demotes the previous default in the same operation. Only one coderd_agents_default_model resource should exist per organization. Destroying this resource does not clear the default server-side.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type DefaultModel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DefaultModelSpec   `json:"spec"`
	Status            DefaultModelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DefaultModelList contains a list of DefaultModels
type DefaultModelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DefaultModel `json:"items"`
}

// Repository type metadata.
var (
	DefaultModel_Kind             = "DefaultModel"
	DefaultModel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DefaultModel_Kind}.String()
	DefaultModel_KindAPIVersion   = DefaultModel_Kind + "." + CRDGroupVersion.String()
	DefaultModel_GroupVersionKind = CRDGroupVersion.WithKind(DefaultModel_Kind)
)

func init() {
	SchemeBuilder.Register(&DefaultModel{}, &DefaultModelList{})
}
