// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MCPServerInitParameters struct {

	// (String) HTTP header used for API key authentication. It must be configured when creating a server with auth_type = "api_key" or changing its auth type to it.
	// HTTP header used for API key authentication. It must be configured when creating a server with `auth_type = "api_key"` or changing its auth type to it.
	APIKeyHeader *string `json:"apiKeyHeader,omitempty" tf:"api_key_header,omitempty"`

	// only) API key value. Bump api_key_value_wo_version to rotate it.
	// API key value. Bump `api_key_value_wo_version` to rotate it.
	APIKeyValueWoSecretRef *v2.LocalSecretKeySelector `json:"apiKeyValueWoSecretRef,omitempty" tf:"-"`

	// only API key value. Bump it whenever the value changes.
	// Version for the write-only API key value. Bump it whenever the value changes.
	APIKeyValueWoVersion *float64 `json:"apiKeyValueWoVersion,omitempty" tf:"api_key_value_wo_version,omitempty"`

	// (Boolean) Whether tools from this server are available in plan mode. Defaults to false.
	// Whether tools from this server are available in plan mode. Defaults to false.
	AllowInPlanMode *bool `json:"allowInPlanMode,omitempty" tf:"allow_in_plan_mode,omitempty"`

	// (String) Authentication type. Valid values are none, oauth2, api_key, custom_headers, and user_oidc. Defaults to none. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
	// Authentication type. Valid values are `none`, `oauth2`, `api_key`, `custom_headers`, and `user_oidc`. Defaults to `none`. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) Availability policy. Valid values are force_on, default_on, and default_off. Defaults to default_off.
	// Availability policy. Valid values are `force_on`, `default_on`, and `default_off`. Defaults to `default_off`.
	Availability *string `json:"availability,omitempty" tf:"availability,omitempty"`

	CustomHeadersWo map[string]*string `json:"customHeadersWoSecretRef,omitempty" tf:"-"`

	// only custom headers. Bump it whenever the map changes.
	// Version for the write-only custom headers. Bump it whenever the map changes.
	CustomHeadersWoVersion *float64 `json:"customHeadersWoVersion,omitempty" tf:"custom_headers_wo_version,omitempty"`

	// (String) Description shown in Coder.
	// Description shown in Coder.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Display name shown in Coder.
	// Display name shown in Coder.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether the MCP server is enabled. Defaults to false.
	// Whether the MCP server is enabled. Defaults to false.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
	// Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
	ForwardCoderHeaders *bool `json:"forwardCoderHeaders,omitempty" tf:"forward_coder_headers,omitempty"`

	// (String) Icon URL shown in Coder.
	// Icon URL shown in Coder.
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (Boolean) Whether the model may select this MCP server based on intent. Defaults to false.
	// Whether the model may select this MCP server based on intent. Defaults to false.
	ModelIntent *bool `json:"modelIntent,omitempty" tf:"model_intent,omitempty"`

	// side discovery.
	// OAuth2 authorization URL. It can be populated by server-side discovery.
	Oauth2AuthURL *string `json:"oauth2AuthUrl,omitempty" tf:"oauth2_auth_url,omitempty"`

	// (String) OAuth2 client ID. Leave this, oauth2_auth_url, and oauth2_token_url unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 client ID. Leave this, `oauth2_auth_url`, and `oauth2_token_url` unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// only) OAuth2 client secret. Bump oauth2_client_secret_wo_version to rotate it.
	// OAuth2 client secret. Bump `oauth2_client_secret_wo_version` to rotate it.
	Oauth2ClientSecretWoSecretRef *v2.LocalSecretKeySelector `json:"oauth2ClientSecretWoSecretRef,omitempty" tf:"-"`

	// only OAuth2 client secret. Bump it whenever the secret changes.
	// Version for the write-only OAuth2 client secret. Bump it whenever the secret changes.
	Oauth2ClientSecretWoVersion *float64 `json:"oauth2ClientSecretWoVersion,omitempty" tf:"oauth2_client_secret_wo_version,omitempty"`

	// side discovery. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 token revocation URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
	Oauth2RevocationURL *string `json:"oauth2RevocationUrl,omitempty" tf:"oauth2_revocation_url,omitempty"`

	// separated OAuth2 scopes.
	// Space-separated OAuth2 scopes.
	Oauth2Scopes *string `json:"oauth2Scopes,omitempty" tf:"oauth2_scopes,omitempty"`

	// side discovery. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 token URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
	Oauth2TokenURL *string `json:"oauth2TokenUrl,omitempty" tf:"oauth2_token_url,omitempty"`

	// (String) Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
	// Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`

	// unique slug for the MCP server. The slug can be updated in place.
	// Organization-unique slug for the MCP server. The slug can be updated in place.
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (Set of String) Tool names that are allowed. An empty set allows all tools unless denied.
	// Tool names that are allowed. An empty set allows all tools unless denied.
	// +listType=set
	ToolAllowList []*string `json:"toolAllowList,omitempty" tf:"tool_allow_list,omitempty"`

	// (Set of String) Tool names that are denied.
	// Tool names that are denied.
	// +listType=set
	ToolDenyList []*string `json:"toolDenyList,omitempty" tf:"tool_deny_list,omitempty"`

	// (String) MCP transport. Valid values are streamable_http and sse. Defaults to streamable_http.
	// MCP transport. Valid values are `streamable_http` and `sse`. Defaults to `streamable_http`.
	Transport *string `json:"transport,omitempty" tf:"transport,omitempty"`

	// (String) MCP server URL. Changing this value invalidates users' stored OAuth tokens.
	// MCP server URL. Changing this value invalidates users' stored OAuth tokens.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type MCPServerObservation struct {

	// (String) HTTP header used for API key authentication. It must be configured when creating a server with auth_type = "api_key" or changing its auth type to it.
	// HTTP header used for API key authentication. It must be configured when creating a server with `auth_type = "api_key"` or changing its auth type to it.
	APIKeyHeader *string `json:"apiKeyHeader,omitempty" tf:"api_key_header,omitempty"`

	// only API key value. Bump it whenever the value changes.
	// Version for the write-only API key value. Bump it whenever the value changes.
	APIKeyValueWoVersion *float64 `json:"apiKeyValueWoVersion,omitempty" tf:"api_key_value_wo_version,omitempty"`

	// (Boolean) Whether tools from this server are available in plan mode. Defaults to false.
	// Whether tools from this server are available in plan mode. Defaults to false.
	AllowInPlanMode *bool `json:"allowInPlanMode,omitempty" tf:"allow_in_plan_mode,omitempty"`

	// (String) Authentication type. Valid values are none, oauth2, api_key, custom_headers, and user_oidc. Defaults to none. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
	// Authentication type. Valid values are `none`, `oauth2`, `api_key`, `custom_headers`, and `user_oidc`. Defaults to `none`. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) Availability policy. Valid values are force_on, default_on, and default_off. Defaults to default_off.
	// Availability policy. Valid values are `force_on`, `default_on`, and `default_off`. Defaults to `default_off`.
	Availability *string `json:"availability,omitempty" tf:"availability,omitempty"`

	// (Number) Unix timestamp when the MCP server configuration was created.
	// Unix timestamp when the MCP server configuration was created.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// only custom headers. Bump it whenever the map changes.
	// Version for the write-only custom headers. Bump it whenever the map changes.
	CustomHeadersWoVersion *float64 `json:"customHeadersWoVersion,omitempty" tf:"custom_headers_wo_version,omitempty"`

	// (String) Description shown in Coder.
	// Description shown in Coder.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Display name shown in Coder.
	// Display name shown in Coder.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether the MCP server is enabled. Defaults to false.
	// Whether the MCP server is enabled. Defaults to false.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
	// Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
	ForwardCoderHeaders *bool `json:"forwardCoderHeaders,omitempty" tf:"forward_coder_headers,omitempty"`

	// (String) MCP server configuration ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Icon URL shown in Coder.
	// Icon URL shown in Coder.
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (Boolean) Whether the model may select this MCP server based on intent. Defaults to false.
	// Whether the model may select this MCP server based on intent. Defaults to false.
	ModelIntent *bool `json:"modelIntent,omitempty" tf:"model_intent,omitempty"`

	// side discovery.
	// OAuth2 authorization URL. It can be populated by server-side discovery.
	Oauth2AuthURL *string `json:"oauth2AuthUrl,omitempty" tf:"oauth2_auth_url,omitempty"`

	// (String) OAuth2 client ID. Leave this, oauth2_auth_url, and oauth2_token_url unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 client ID. Leave this, `oauth2_auth_url`, and `oauth2_token_url` unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// only OAuth2 client secret. Bump it whenever the secret changes.
	// Version for the write-only OAuth2 client secret. Bump it whenever the secret changes.
	Oauth2ClientSecretWoVersion *float64 `json:"oauth2ClientSecretWoVersion,omitempty" tf:"oauth2_client_secret_wo_version,omitempty"`

	// side discovery. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 token revocation URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
	Oauth2RevocationURL *string `json:"oauth2RevocationUrl,omitempty" tf:"oauth2_revocation_url,omitempty"`

	// separated OAuth2 scopes.
	// Space-separated OAuth2 scopes.
	Oauth2Scopes *string `json:"oauth2Scopes,omitempty" tf:"oauth2_scopes,omitempty"`

	// side discovery. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 token URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
	Oauth2TokenURL *string `json:"oauth2TokenUrl,omitempty" tf:"oauth2_token_url,omitempty"`

	// (String) Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
	// Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// unique slug for the MCP server. The slug can be updated in place.
	// Organization-unique slug for the MCP server. The slug can be updated in place.
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (Set of String) Tool names that are allowed. An empty set allows all tools unless denied.
	// Tool names that are allowed. An empty set allows all tools unless denied.
	// +listType=set
	ToolAllowList []*string `json:"toolAllowList,omitempty" tf:"tool_allow_list,omitempty"`

	// (Set of String) Tool names that are denied.
	// Tool names that are denied.
	// +listType=set
	ToolDenyList []*string `json:"toolDenyList,omitempty" tf:"tool_deny_list,omitempty"`

	// (String) MCP transport. Valid values are streamable_http and sse. Defaults to streamable_http.
	// MCP transport. Valid values are `streamable_http` and `sse`. Defaults to `streamable_http`.
	Transport *string `json:"transport,omitempty" tf:"transport,omitempty"`

	// (String) MCP server URL. Changing this value invalidates users' stored OAuth tokens.
	// MCP server URL. Changing this value invalidates users' stored OAuth tokens.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Number) Unix timestamp when the MCP server configuration was last updated.
	// Unix timestamp when the MCP server configuration was last updated.
	UpdatedAt *float64 `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type MCPServerParameters struct {

	// (String) HTTP header used for API key authentication. It must be configured when creating a server with auth_type = "api_key" or changing its auth type to it.
	// HTTP header used for API key authentication. It must be configured when creating a server with `auth_type = "api_key"` or changing its auth type to it.
	// +kubebuilder:validation:Optional
	APIKeyHeader *string `json:"apiKeyHeader,omitempty" tf:"api_key_header,omitempty"`

	// only) API key value. Bump api_key_value_wo_version to rotate it.
	// API key value. Bump `api_key_value_wo_version` to rotate it.
	// +kubebuilder:validation:Optional
	APIKeyValueWoSecretRef *v2.LocalSecretKeySelector `json:"apiKeyValueWoSecretRef,omitempty" tf:"-"`

	// only API key value. Bump it whenever the value changes.
	// Version for the write-only API key value. Bump it whenever the value changes.
	// +kubebuilder:validation:Optional
	APIKeyValueWoVersion *float64 `json:"apiKeyValueWoVersion,omitempty" tf:"api_key_value_wo_version,omitempty"`

	// (Boolean) Whether tools from this server are available in plan mode. Defaults to false.
	// Whether tools from this server are available in plan mode. Defaults to false.
	// +kubebuilder:validation:Optional
	AllowInPlanMode *bool `json:"allowInPlanMode,omitempty" tf:"allow_in_plan_mode,omitempty"`

	// (String) Authentication type. Valid values are none, oauth2, api_key, custom_headers, and user_oidc. Defaults to none. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
	// Authentication type. Valid values are `none`, `oauth2`, `api_key`, `custom_headers`, and `user_oidc`. Defaults to `none`. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) Availability policy. Valid values are force_on, default_on, and default_off. Defaults to default_off.
	// Availability policy. Valid values are `force_on`, `default_on`, and `default_off`. Defaults to `default_off`.
	// +kubebuilder:validation:Optional
	Availability *string `json:"availability,omitempty" tf:"availability,omitempty"`

	// only) HTTP headers used for custom header authentication. Bump custom_headers_wo_version to replace them.
	// HTTP headers used for custom header authentication. Bump `custom_headers_wo_version` to replace them.
	// +kubebuilder:validation:Optional
	CustomHeadersWoSecretRef *v2.LocalSecretReference `json:"customHeadersWoSecretRef,omitempty" tf:"-"`

	// only custom headers. Bump it whenever the map changes.
	// Version for the write-only custom headers. Bump it whenever the map changes.
	// +kubebuilder:validation:Optional
	CustomHeadersWoVersion *float64 `json:"customHeadersWoVersion,omitempty" tf:"custom_headers_wo_version,omitempty"`

	// (String) Description shown in Coder.
	// Description shown in Coder.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Display name shown in Coder.
	// Display name shown in Coder.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether the MCP server is enabled. Defaults to false.
	// Whether the MCP server is enabled. Defaults to false.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
	// Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
	// +kubebuilder:validation:Optional
	ForwardCoderHeaders *bool `json:"forwardCoderHeaders,omitempty" tf:"forward_coder_headers,omitempty"`

	// (String) Icon URL shown in Coder.
	// Icon URL shown in Coder.
	// +kubebuilder:validation:Optional
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (Boolean) Whether the model may select this MCP server based on intent. Defaults to false.
	// Whether the model may select this MCP server based on intent. Defaults to false.
	// +kubebuilder:validation:Optional
	ModelIntent *bool `json:"modelIntent,omitempty" tf:"model_intent,omitempty"`

	// side discovery.
	// OAuth2 authorization URL. It can be populated by server-side discovery.
	// +kubebuilder:validation:Optional
	Oauth2AuthURL *string `json:"oauth2AuthUrl,omitempty" tf:"oauth2_auth_url,omitempty"`

	// (String) OAuth2 client ID. Leave this, oauth2_auth_url, and oauth2_token_url unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 client ID. Leave this, `oauth2_auth_url`, and `oauth2_token_url` unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
	// +kubebuilder:validation:Optional
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// only) OAuth2 client secret. Bump oauth2_client_secret_wo_version to rotate it.
	// OAuth2 client secret. Bump `oauth2_client_secret_wo_version` to rotate it.
	// +kubebuilder:validation:Optional
	Oauth2ClientSecretWoSecretRef *v2.LocalSecretKeySelector `json:"oauth2ClientSecretWoSecretRef,omitempty" tf:"-"`

	// only OAuth2 client secret. Bump it whenever the secret changes.
	// Version for the write-only OAuth2 client secret. Bump it whenever the secret changes.
	// +kubebuilder:validation:Optional
	Oauth2ClientSecretWoVersion *float64 `json:"oauth2ClientSecretWoVersion,omitempty" tf:"oauth2_client_secret_wo_version,omitempty"`

	// side discovery. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 token revocation URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
	// +kubebuilder:validation:Optional
	Oauth2RevocationURL *string `json:"oauth2RevocationUrl,omitempty" tf:"oauth2_revocation_url,omitempty"`

	// separated OAuth2 scopes.
	// Space-separated OAuth2 scopes.
	// +kubebuilder:validation:Optional
	Oauth2Scopes *string `json:"oauth2Scopes,omitempty" tf:"oauth2_scopes,omitempty"`

	// side discovery. Changing it invalidates users' stored OAuth tokens.
	// OAuth2 token URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
	// +kubebuilder:validation:Optional
	Oauth2TokenURL *string `json:"oauth2TokenUrl,omitempty" tf:"oauth2_token_url,omitempty"`

	// (String) Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
	// Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`

	// unique slug for the MCP server. The slug can be updated in place.
	// Organization-unique slug for the MCP server. The slug can be updated in place.
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (Set of String) Tool names that are allowed. An empty set allows all tools unless denied.
	// Tool names that are allowed. An empty set allows all tools unless denied.
	// +kubebuilder:validation:Optional
	// +listType=set
	ToolAllowList []*string `json:"toolAllowList,omitempty" tf:"tool_allow_list,omitempty"`

	// (Set of String) Tool names that are denied.
	// Tool names that are denied.
	// +kubebuilder:validation:Optional
	// +listType=set
	ToolDenyList []*string `json:"toolDenyList,omitempty" tf:"tool_deny_list,omitempty"`

	// (String) MCP transport. Valid values are streamable_http and sse. Defaults to streamable_http.
	// MCP transport. Valid values are `streamable_http` and `sse`. Defaults to `streamable_http`.
	// +kubebuilder:validation:Optional
	Transport *string `json:"transport,omitempty" tf:"transport,omitempty"`

	// (String) MCP server URL. Changing this value invalidates users' stored OAuth tokens.
	// MCP server URL. Changing this value invalidates users' stored OAuth tokens.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// MCPServerSpec defines the desired state of MCPServer
type MCPServerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MCPServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MCPServerInitParameters `json:"initProvider,omitempty"`
}

// MCPServerStatus defines the observed state of MCPServer.
type MCPServerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MCPServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MCPServer is the Schema for the MCPServers API. ~> This resource is experimental. Changes are expected, and it is not recommended for production use. ~> Warning This resource is only compatible with Coder version 2.37.0 https://github.com/coder/coder/releases/tag/v2.37.0 and later. -> _wo attributes are write-only https://developer.hashicorp.11 or later. Configures an organization-scoped MCP server for Coder Agents. Import IDs use
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type MCPServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.slug) || (has(self.initProvider) && has(self.initProvider.slug))",message="spec.forProvider.slug is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   MCPServerSpec   `json:"spec"`
	Status MCPServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MCPServerList contains a list of MCPServers
type MCPServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MCPServer `json:"items"`
}

// Repository type metadata.
var (
	MCPServer_Kind             = "MCPServer"
	MCPServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MCPServer_Kind}.String()
	MCPServer_KindAPIVersion   = MCPServer_Kind + "." + CRDGroupVersion.String()
	MCPServer_GroupVersionKind = CRDGroupVersion.WithKind(MCPServer_Kind)
)

func init() {
	SchemeBuilder.Register(&MCPServer{}, &MCPServerList{})
}
