// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ModelInitParameters struct {

	// derives the read-only provider_type from the referenced provider.
	// AI provider ID that backs this model. Usually this is `coderd_ai_provider.<name>.id`. Updating it re-derives the read-only `provider_type` from the referenced provider.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/agents/v1alpha1.AIProvider
	AIProviderID *string `json:"aiProviderId,omitempty" tf:"ai_provider_id,omitempty"`

	// Reference to a AIProvider in agents to populate aiProviderId.
	// +kubebuilder:validation:Optional
	AIProviderIDRef *v2.NamespacedReference `json:"aiProviderIdRef,omitempty" tf:"-"`

	// Selector for a AIProvider in agents to populate aiProviderId.
	// +kubebuilder:validation:Optional
	AIProviderIDSelector *v2.NamespacedSelector `json:"aiProviderIdSelector,omitempty" tf:"-"`

	// (Number) Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
	// Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
	CompressionThreshold *float64 `json:"compressionThreshold,omitempty" tf:"compression_threshold,omitempty"`

	// (Number) Maximum context window for this model. Must be greater than zero.
	// Maximum context window for this model. Must be greater than zero.
	ContextLimit *float64 `json:"contextLimit,omitempty" tf:"context_limit,omitempty"`

	// (String) Display name shown in Coder.
	// Display name shown in Coder.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether this model configuration is enabled. Defaults to true.
	// Whether this model configuration is enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Model identifier to use with the referenced provider.
	// Model identifier to use with the referenced provider.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// call tuning for the model, such as max_output_tokens, temperature, top_p, and provider_options. See the field reference (including per-provider provider_options) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
	// Optional JSON blob of per-call tuning for the model, such as `max_output_tokens`, `temperature`, `top_p`, and `provider_options`. See the field reference (including per-provider `provider_options`) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
	ModelConfig *string `json:"modelConfig,omitempty" tf:"model_config,omitempty"`

	// (String) Organization ID that owns the Agents model configuration. Defaults to the provider default organization ID.
	// Organization ID that owns the Agents model configuration. Defaults to the provider default organization ID.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`
}

type ModelObservation struct {

	// derives the read-only provider_type from the referenced provider.
	// AI provider ID that backs this model. Usually this is `coderd_ai_provider.<name>.id`. Updating it re-derives the read-only `provider_type` from the referenced provider.
	AIProviderID *string `json:"aiProviderId,omitempty" tf:"ai_provider_id,omitempty"`

	// (Number) Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
	// Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
	CompressionThreshold *float64 `json:"compressionThreshold,omitempty" tf:"compression_threshold,omitempty"`

	// (Number) Maximum context window for this model. Must be greater than zero.
	// Maximum context window for this model. Must be greater than zero.
	ContextLimit *float64 `json:"contextLimit,omitempty" tf:"context_limit,omitempty"`

	// (Number) Creation timestamp as Unix seconds.
	// Creation timestamp as Unix seconds.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Display name shown in Coder.
	// Display name shown in Coder.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether this model configuration is enabled. Defaults to true.
	// Whether this model configuration is enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Agents model configuration ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Model identifier to use with the referenced provider.
	// Model identifier to use with the referenced provider.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// call tuning for the model, such as max_output_tokens, temperature, top_p, and provider_options. See the field reference (including per-provider provider_options) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
	// Optional JSON blob of per-call tuning for the model, such as `max_output_tokens`, `temperature`, `top_p`, and `provider_options`. See the field reference (including per-provider `provider_options`) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
	ModelConfig *string `json:"modelConfig,omitempty" tf:"model_config,omitempty"`

	// (String) Organization ID that owns the Agents model configuration. Defaults to the provider default organization ID.
	// Organization ID that owns the Agents model configuration. Defaults to the provider default organization ID.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) Provider type derived by Coder from ai_provider_id, for example openai, anthropic, or bedrock.
	// Provider type derived by Coder from `ai_provider_id`, for example `openai`, `anthropic`, or `bedrock`.
	ProviderType *string `json:"providerType,omitempty" tf:"provider_type,omitempty"`

	// (Number) Last update timestamp as Unix seconds.
	// Last update timestamp as Unix seconds.
	UpdatedAt *float64 `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ModelParameters struct {

	// derives the read-only provider_type from the referenced provider.
	// AI provider ID that backs this model. Usually this is `coderd_ai_provider.<name>.id`. Updating it re-derives the read-only `provider_type` from the referenced provider.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/agents/v1alpha1.AIProvider
	// +kubebuilder:validation:Optional
	AIProviderID *string `json:"aiProviderId,omitempty" tf:"ai_provider_id,omitempty"`

	// Reference to a AIProvider in agents to populate aiProviderId.
	// +kubebuilder:validation:Optional
	AIProviderIDRef *v2.NamespacedReference `json:"aiProviderIdRef,omitempty" tf:"-"`

	// Selector for a AIProvider in agents to populate aiProviderId.
	// +kubebuilder:validation:Optional
	AIProviderIDSelector *v2.NamespacedSelector `json:"aiProviderIdSelector,omitempty" tf:"-"`

	// (Number) Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
	// Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
	// +kubebuilder:validation:Optional
	CompressionThreshold *float64 `json:"compressionThreshold,omitempty" tf:"compression_threshold,omitempty"`

	// (Number) Maximum context window for this model. Must be greater than zero.
	// Maximum context window for this model. Must be greater than zero.
	// +kubebuilder:validation:Optional
	ContextLimit *float64 `json:"contextLimit,omitempty" tf:"context_limit,omitempty"`

	// (String) Display name shown in Coder.
	// Display name shown in Coder.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether this model configuration is enabled. Defaults to true.
	// Whether this model configuration is enabled. Defaults to true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Model identifier to use with the referenced provider.
	// Model identifier to use with the referenced provider.
	// +kubebuilder:validation:Optional
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// call tuning for the model, such as max_output_tokens, temperature, top_p, and provider_options. See the field reference (including per-provider provider_options) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
	// Optional JSON blob of per-call tuning for the model, such as `max_output_tokens`, `temperature`, `top_p`, and `provider_options`. See the field reference (including per-provider `provider_options`) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
	// +kubebuilder:validation:Optional
	ModelConfig *string `json:"modelConfig,omitempty" tf:"model_config,omitempty"`

	// (String) Organization ID that owns the Agents model configuration. Defaults to the provider default organization ID.
	// Organization ID that owns the Agents model configuration. Defaults to the provider default organization ID.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`
}

// ModelSpec defines the desired state of Model
type ModelSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ModelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ModelInitParameters `json:"initProvider,omitempty"`
}

// ModelStatus defines the observed state of Model.
type ModelStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ModelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Model is the Schema for the Models API. ~> This resource is experimental. Changes are to be expected, and we recommend using it with caution in production environments. ~> Warning This resource is only compatible with Coder version 2.37.0 https://github.com/coder/coder/releases/tag/v2.37.0 and later. Configures an organization-scoped, admin-managed chat model for Coder Agents, binding a model identifier to a configured AI provider (see coderd_ai_provider) along with context, compression, and optional JSON tuning settings. Import IDs use
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type Model struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.contextLimit) || (has(self.initProvider) && has(self.initProvider.contextLimit))",message="spec.forProvider.contextLimit is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.model) || (has(self.initProvider) && has(self.initProvider.model))",message="spec.forProvider.model is a required parameter"
	Spec   ModelSpec   `json:"spec"`
	Status ModelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ModelList contains a list of Models
type ModelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Model `json:"items"`
}

// Repository type metadata.
var (
	Model_Kind             = "Model"
	Model_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Model_Kind}.String()
	Model_KindAPIVersion   = Model_Kind + "." + CRDGroupVersion.String()
	Model_GroupVersionKind = CRDGroupVersion.WithKind(Model_Kind)
)

func init() {
	SchemeBuilder.Register(&Model{}, &ModelList{})
}
