// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ProvisionerKeyInitParameters struct {

	// (String) The name of the key.
	// The name of the key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization that provisioners connected with this key will be connected to.
	// The organization that provisioners connected with this key will be connected to.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.Reference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.Selector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (Map of String) The tags that provisioners connected with this key will accept jobs for.
	// The tags that provisioners connected with this key will accept jobs for.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ProvisionerKeyObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the key.
	// The name of the key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization that provisioners connected with this key will be connected to.
	// The organization that provisioners connected with this key will be connected to.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (Map of String) The tags that provisioners connected with this key will accept jobs for.
	// The tags that provisioners connected with this key will accept jobs for.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ProvisionerKeyParameters struct {

	// (String) The name of the key.
	// The name of the key.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization that provisioners connected with this key will be connected to.
	// The organization that provisioners connected with this key will be connected to.
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/cluster/iam/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.Reference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.Selector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (Map of String) The tags that provisioners connected with this key will accept jobs for.
	// The tags that provisioners connected with this key will accept jobs for.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// ProvisionerKeySpec defines the desired state of ProvisionerKey
type ProvisionerKeySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ProvisionerKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProvisionerKeyInitParameters `json:"initProvider,omitempty"`
}

// ProvisionerKeyStatus defines the observed state of ProvisionerKey.
type ProvisionerKeyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ProvisionerKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProvisionerKey is the Schema for the ProvisionerKeys API. A provisioner key for a Coder deployment.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coderd}
type ProvisionerKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProvisionerKeySpec   `json:"spec"`
	Status ProvisionerKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProvisionerKeyList contains a list of ProvisionerKeys
type ProvisionerKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProvisionerKey `json:"items"`
}

// Repository type metadata.
var (
	ProvisionerKey_Kind             = "ProvisionerKey"
	ProvisionerKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProvisionerKey_Kind}.String()
	ProvisionerKey_KindAPIVersion   = ProvisionerKey_Kind + "." + CRDGroupVersion.String()
	ProvisionerKey_GroupVersionKind = CRDGroupVersion.WithKind(ProvisionerKey_Kind)
)

func init() {
	SchemeBuilder.Register(&ProvisionerKey{}, &ProvisionerKeyList{})
}
