apiVersion: iam.coderd.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/user
  labels:
    testing.upbound.io/example-name: jenkins
  name: jenkins
  namespace: crossplane-system
spec:
  forProvider:
    email: ci@example.com
    loginType: none
    name: Jenkins CI/CD
    roles:
    - template-admin
    username: jenkins
