apiVersion: template.coderd.m.crossplane.io/v1alpha1
kind: Template
metadata:
  annotations:
    meta.upbound.io/example-id: template/v1alpha1/template
  labels:
    testing.upbound.io/example-name: ubuntu-main
  name: ubuntu-main
  namespace: crossplane-system
spec:
  forProvider:
    acl:
      groups: []
      users:
      - id: ${coderd_user.coder1.id}
        role: admin
    description: The main template for developing on Ubuntu.
    name: ubuntu-main
    versions:
    - description: The stable version of the template.
      directory: ./stable-template
      name: stable-${var.COMMIT_SHA}
    - description: The staging version of the template.
      directory: ./staging-template
      name: staging-${var.COMMIT_SHA}

---

apiVersion: iam.coderd.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: template/v1alpha1/template
  labels:
    testing.upbound.io/example-name: coder1
  name: coder1
  namespace: crossplane-system
spec:
  forProvider:
    email: coder1@coder.com
    name: Coder One
    username: coder1
