// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ACLInitParameters struct {

	// (Attributes Set) (see below for nested schema)
	Groups []GroupsInitParameters `json:"groups,omitempty" tf:"groups,omitempty"`

	// (Attributes Set) (see below for nested schema)
	Users []UsersInitParameters `json:"users,omitempty" tf:"users,omitempty"`
}

type ACLObservation struct {

	// (Attributes Set) (see below for nested schema)
	Groups []GroupsObservation `json:"groups,omitempty" tf:"groups,omitempty"`

	// (Attributes Set) (see below for nested schema)
	Users []UsersObservation `json:"users,omitempty" tf:"users,omitempty"`
}

type ACLParameters struct {

	// (Attributes Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Groups []GroupsParameters `json:"groups" tf:"groups,omitempty"`

	// (Attributes Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Users []UsersParameters `json:"users" tf:"users,omitempty"`
}

type AutoStopRequirementInitParameters struct {

	// (Set of String) List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
	// List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
	// +listType=set
	DaysOfWeek []*string `json:"daysOfWeek,omitempty" tf:"days_of_week,omitempty"`

	// (Number) Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
	// Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
	Weeks *float64 `json:"weeks,omitempty" tf:"weeks,omitempty"`
}

type AutoStopRequirementObservation struct {

	// (Set of String) List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
	// List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
	// +listType=set
	DaysOfWeek []*string `json:"daysOfWeek,omitempty" tf:"days_of_week,omitempty"`

	// (Number) Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
	// Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
	Weeks *float64 `json:"weeks,omitempty" tf:"weeks,omitempty"`
}

type AutoStopRequirementParameters struct {

	// (Set of String) List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
	// List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
	// +kubebuilder:validation:Optional
	// +listType=set
	DaysOfWeek []*string `json:"daysOfWeek,omitempty" tf:"days_of_week,omitempty"`

	// (Number) Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
	// Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
	// +kubebuilder:validation:Optional
	Weeks *float64 `json:"weeks,omitempty" tf:"weeks,omitempty"`
}

type GroupsInitParameters struct {

	// (String) The ID of the template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Role assigned to the user or group. Valid roles are admin and use.
	// Role assigned to the user or group. Valid roles are `admin` and `use`.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type GroupsObservation struct {

	// (String) The ID of the template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Role assigned to the user or group. Valid roles are admin and use.
	// Role assigned to the user or group. Valid roles are `admin` and `use`.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type GroupsParameters struct {

	// (String) The ID of the template.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Role assigned to the user or group. Valid roles are admin and use.
	// Role assigned to the user or group. Valid roles are `admin` and `use`.
	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role,omitempty"`
}

type ProvisionerTagsInitParameters struct {

	// (String) The name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProvisionerTagsObservation struct {

	// (String) The name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProvisionerTagsParameters struct {

	// (String) The name of the template.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type TemplateInitParameters struct {

	// (Attributes) (Enterprise) Access control list for the template. (see below for nested schema)
	ACL *ACLInitParameters `json:"acl,omitempty" tf:"acl,omitempty"`

	// (Number) The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
	// The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
	ActivityBumpMs *float64 `json:"activityBumpMs,omitempty" tf:"activity_bump_ms,omitempty"`

	// (Boolean) Whether Coder Agents can create workspaces from this template. Coder defaults this setting to true. Requires a Coder deployment running v2.37.0 or later.
	// Whether Coder Agents can create workspaces from this template. Coder defaults this setting to true. Requires a Coder deployment running v2.37.0 or later.
	AgentsAllowed *bool `json:"agentsAllowed,omitempty" tf:"agents_allowed,omitempty"`

	// start workspaces created from this template. Defaults to true.
	// (Enterprise) Whether users can auto-start workspaces created from this template. Defaults to true.
	AllowUserAutoStart *bool `json:"allowUserAutoStart,omitempty" tf:"allow_user_auto_start,omitempty"`

	// stop workspaces created from this template. Defaults to true.
	// (Enterprise) Whether users can auto-stop workspaces created from this template. Defaults to true.
	AllowUserAutoStop *bool `json:"allowUserAutoStop,omitempty" tf:"allow_user_auto_stop,omitempty"`

	// progress workspace jobs using this template. Defaults to true.
	// Whether users can cancel in-progress workspace jobs using this template. Defaults to true.
	AllowUserCancelWorkspaceJobs *bool `json:"allowUserCancelWorkspaceJobs,omitempty" tf:"allow_user_cancel_workspace_jobs,omitempty"`

	// (Set of String) (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
	// (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
	// +listType=set
	AutoStartPermittedDaysOfWeek []*string `json:"autoStartPermittedDaysOfWeek,omitempty" tf:"auto_start_permitted_days_of_week,omitempty"`

	// stop requirement for all workspaces created from this template. (see below for nested schema)
	AutoStopRequirement *AutoStopRequirementInitParameters `json:"autoStopRequirement,omitempty" tf:"auto_stop_requirement,omitempty"`

	// (String) The CORS behavior for workspace apps in this template. Valid values are simple (default CORS middleware) or passthru (bypass CORS middleware). Defaults to simple. Requires a Coder deployment running v2.26.0 or later.
	// The CORS behavior for workspace apps in this template. Valid values are `simple` (default CORS middleware) or `passthru` (bypass CORS middleware). Defaults to `simple`. Requires a Coder deployment running v2.26.0 or later.
	CorsBehavior *string `json:"corsBehavior,omitempty" tf:"cors_behavior,omitempty"`

	// to-live for all workspaces created from this template, in milliseconds.
	// The default time-to-live for all workspaces created from this template, in milliseconds.
	DefaultTTLMs *float64 `json:"defaultTtlMs,omitempty" tf:"default_ttl_ms,omitempty"`

	// (String) If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
	// If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
	DeprecationMessage *string `json:"deprecationMessage,omitempty" tf:"deprecation_message,omitempty"`

	// (String) A description of the template.
	// A description of the template.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name of the template. Defaults to the template name.
	// The display name of the template. Defaults to the template name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
	// (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
	FailureTTLMs *float64 `json:"failureTtlMs,omitempty" tf:"failure_ttl_ms,omitempty"`

	// (String) Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// Relative path or external URL that specifies an icon to be displayed in the dashboard.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) (Enterprise) The maximum port share level for workspaces created from this template. Defaults to owner on an Enterprise deployment, or public otherwise.
	// (Enterprise) The maximum port share level for workspaces created from this template. Defaults to `owner` on an Enterprise deployment, or `public` otherwise.
	MaxPortShareLevel *string `json:"maxPortShareLevel,omitempty" tf:"max_port_share_level,omitempty"`

	// (String) The name of the template.
	// The name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the organization. Defaults to the provider's default organization
	// The ID of the organization. Defaults to the provider's default organization
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (Boolean) (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
	// (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
	RequireActiveVersion *bool `json:"requireActiveVersion,omitempty" tf:"require_active_version,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
	// (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
	TimeTilDormantAutodeleteMs *float64 `json:"timeTilDormantAutodeleteMs,omitempty" tf:"time_til_dormant_autodelete_ms,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
	// (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
	TimeTilDormantMs *float64 `json:"timeTilDormantMs,omitempty" tf:"time_til_dormant_ms,omitempty"`

	// (Boolean) If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
	// If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
	UseClassicParameterFlow *bool `json:"useClassicParameterFlow,omitempty" tf:"use_classic_parameter_flow,omitempty"`

	// (Attributes List) The template versions to manage. At least one version (with active = true) is required when creating a new template, since Coder templates cannot exist without a version. (see below for nested schema)
	Versions []VersionsInitParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type TemplateObservation struct {

	// (Attributes) (Enterprise) Access control list for the template. (see below for nested schema)
	ACL *ACLObservation `json:"acl,omitempty" tf:"acl,omitempty"`

	// (Number) The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
	// The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
	ActivityBumpMs *float64 `json:"activityBumpMs,omitempty" tf:"activity_bump_ms,omitempty"`

	// (Boolean) Whether Coder Agents can create workspaces from this template. Coder defaults this setting to true. Requires a Coder deployment running v2.37.0 or later.
	// Whether Coder Agents can create workspaces from this template. Coder defaults this setting to true. Requires a Coder deployment running v2.37.0 or later.
	AgentsAllowed *bool `json:"agentsAllowed,omitempty" tf:"agents_allowed,omitempty"`

	// start workspaces created from this template. Defaults to true.
	// (Enterprise) Whether users can auto-start workspaces created from this template. Defaults to true.
	AllowUserAutoStart *bool `json:"allowUserAutoStart,omitempty" tf:"allow_user_auto_start,omitempty"`

	// stop workspaces created from this template. Defaults to true.
	// (Enterprise) Whether users can auto-stop workspaces created from this template. Defaults to true.
	AllowUserAutoStop *bool `json:"allowUserAutoStop,omitempty" tf:"allow_user_auto_stop,omitempty"`

	// progress workspace jobs using this template. Defaults to true.
	// Whether users can cancel in-progress workspace jobs using this template. Defaults to true.
	AllowUserCancelWorkspaceJobs *bool `json:"allowUserCancelWorkspaceJobs,omitempty" tf:"allow_user_cancel_workspace_jobs,omitempty"`

	// (Set of String) (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
	// (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
	// +listType=set
	AutoStartPermittedDaysOfWeek []*string `json:"autoStartPermittedDaysOfWeek,omitempty" tf:"auto_start_permitted_days_of_week,omitempty"`

	// stop requirement for all workspaces created from this template. (see below for nested schema)
	AutoStopRequirement *AutoStopRequirementObservation `json:"autoStopRequirement,omitempty" tf:"auto_stop_requirement,omitempty"`

	// (String) The CORS behavior for workspace apps in this template. Valid values are simple (default CORS middleware) or passthru (bypass CORS middleware). Defaults to simple. Requires a Coder deployment running v2.26.0 or later.
	// The CORS behavior for workspace apps in this template. Valid values are `simple` (default CORS middleware) or `passthru` (bypass CORS middleware). Defaults to `simple`. Requires a Coder deployment running v2.26.0 or later.
	CorsBehavior *string `json:"corsBehavior,omitempty" tf:"cors_behavior,omitempty"`

	// to-live for all workspaces created from this template, in milliseconds.
	// The default time-to-live for all workspaces created from this template, in milliseconds.
	DefaultTTLMs *float64 `json:"defaultTtlMs,omitempty" tf:"default_ttl_ms,omitempty"`

	// (String) If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
	// If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
	DeprecationMessage *string `json:"deprecationMessage,omitempty" tf:"deprecation_message,omitempty"`

	// (String) A description of the template.
	// A description of the template.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name of the template. Defaults to the template name.
	// The display name of the template. Defaults to the template name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
	// (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
	FailureTTLMs *float64 `json:"failureTtlMs,omitempty" tf:"failure_ttl_ms,omitempty"`

	// (String) The ID of the template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// Relative path or external URL that specifies an icon to be displayed in the dashboard.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) (Enterprise) The maximum port share level for workspaces created from this template. Defaults to owner on an Enterprise deployment, or public otherwise.
	// (Enterprise) The maximum port share level for workspaces created from this template. Defaults to `owner` on an Enterprise deployment, or `public` otherwise.
	MaxPortShareLevel *string `json:"maxPortShareLevel,omitempty" tf:"max_port_share_level,omitempty"`

	// (String) The name of the template.
	// The name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the organization. Defaults to the provider's default organization
	// The ID of the organization. Defaults to the provider's default organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (Boolean) (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
	// (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
	RequireActiveVersion *bool `json:"requireActiveVersion,omitempty" tf:"require_active_version,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
	// (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
	TimeTilDormantAutodeleteMs *float64 `json:"timeTilDormantAutodeleteMs,omitempty" tf:"time_til_dormant_autodelete_ms,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
	// (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
	TimeTilDormantMs *float64 `json:"timeTilDormantMs,omitempty" tf:"time_til_dormant_ms,omitempty"`

	// (Boolean) If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
	// If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
	UseClassicParameterFlow *bool `json:"useClassicParameterFlow,omitempty" tf:"use_classic_parameter_flow,omitempty"`

	// (Attributes List) The template versions to manage. At least one version (with active = true) is required when creating a new template, since Coder templates cannot exist without a version. (see below for nested schema)
	Versions []VersionsObservation `json:"versions,omitempty" tf:"versions,omitempty"`
}

type TemplateParameters struct {

	// (Attributes) (Enterprise) Access control list for the template. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ACL *ACLParameters `json:"acl,omitempty" tf:"acl,omitempty"`

	// (Number) The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
	// The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
	// +kubebuilder:validation:Optional
	ActivityBumpMs *float64 `json:"activityBumpMs,omitempty" tf:"activity_bump_ms,omitempty"`

	// (Boolean) Whether Coder Agents can create workspaces from this template. Coder defaults this setting to true. Requires a Coder deployment running v2.37.0 or later.
	// Whether Coder Agents can create workspaces from this template. Coder defaults this setting to true. Requires a Coder deployment running v2.37.0 or later.
	// +kubebuilder:validation:Optional
	AgentsAllowed *bool `json:"agentsAllowed,omitempty" tf:"agents_allowed,omitempty"`

	// start workspaces created from this template. Defaults to true.
	// (Enterprise) Whether users can auto-start workspaces created from this template. Defaults to true.
	// +kubebuilder:validation:Optional
	AllowUserAutoStart *bool `json:"allowUserAutoStart,omitempty" tf:"allow_user_auto_start,omitempty"`

	// stop workspaces created from this template. Defaults to true.
	// (Enterprise) Whether users can auto-stop workspaces created from this template. Defaults to true.
	// +kubebuilder:validation:Optional
	AllowUserAutoStop *bool `json:"allowUserAutoStop,omitempty" tf:"allow_user_auto_stop,omitempty"`

	// progress workspace jobs using this template. Defaults to true.
	// Whether users can cancel in-progress workspace jobs using this template. Defaults to true.
	// +kubebuilder:validation:Optional
	AllowUserCancelWorkspaceJobs *bool `json:"allowUserCancelWorkspaceJobs,omitempty" tf:"allow_user_cancel_workspace_jobs,omitempty"`

	// (Set of String) (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
	// (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
	// +kubebuilder:validation:Optional
	// +listType=set
	AutoStartPermittedDaysOfWeek []*string `json:"autoStartPermittedDaysOfWeek,omitempty" tf:"auto_start_permitted_days_of_week,omitempty"`

	// stop requirement for all workspaces created from this template. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AutoStopRequirement *AutoStopRequirementParameters `json:"autoStopRequirement,omitempty" tf:"auto_stop_requirement,omitempty"`

	// (String) The CORS behavior for workspace apps in this template. Valid values are simple (default CORS middleware) or passthru (bypass CORS middleware). Defaults to simple. Requires a Coder deployment running v2.26.0 or later.
	// The CORS behavior for workspace apps in this template. Valid values are `simple` (default CORS middleware) or `passthru` (bypass CORS middleware). Defaults to `simple`. Requires a Coder deployment running v2.26.0 or later.
	// +kubebuilder:validation:Optional
	CorsBehavior *string `json:"corsBehavior,omitempty" tf:"cors_behavior,omitempty"`

	// to-live for all workspaces created from this template, in milliseconds.
	// The default time-to-live for all workspaces created from this template, in milliseconds.
	// +kubebuilder:validation:Optional
	DefaultTTLMs *float64 `json:"defaultTtlMs,omitempty" tf:"default_ttl_ms,omitempty"`

	// (String) If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
	// If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
	// +kubebuilder:validation:Optional
	DeprecationMessage *string `json:"deprecationMessage,omitempty" tf:"deprecation_message,omitempty"`

	// (String) A description of the template.
	// A description of the template.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name of the template. Defaults to the template name.
	// The display name of the template. Defaults to the template name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
	// (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
	// +kubebuilder:validation:Optional
	FailureTTLMs *float64 `json:"failureTtlMs,omitempty" tf:"failure_ttl_ms,omitempty"`

	// (String) Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// Relative path or external URL that specifies an icon to be displayed in the dashboard.
	// +kubebuilder:validation:Optional
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) (Enterprise) The maximum port share level for workspaces created from this template. Defaults to owner on an Enterprise deployment, or public otherwise.
	// (Enterprise) The maximum port share level for workspaces created from this template. Defaults to `owner` on an Enterprise deployment, or `public` otherwise.
	// +kubebuilder:validation:Optional
	MaxPortShareLevel *string `json:"maxPortShareLevel,omitempty" tf:"max_port_share_level,omitempty"`

	// (String) The name of the template.
	// The name of the template.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the organization. Defaults to the provider's default organization
	// The ID of the organization. Defaults to the provider's default organization
	// +crossplane:generate:reference:type=github.com/axiansinfoma/crossplane-provider-coderd/apis/namespaced/iam/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v2.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v2.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`

	// (Boolean) (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
	// (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
	// +kubebuilder:validation:Optional
	RequireActiveVersion *bool `json:"requireActiveVersion,omitempty" tf:"require_active_version,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
	// (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
	// +kubebuilder:validation:Optional
	TimeTilDormantAutodeleteMs *float64 `json:"timeTilDormantAutodeleteMs,omitempty" tf:"time_til_dormant_autodelete_ms,omitempty"`

	// (Number) (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
	// (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
	// +kubebuilder:validation:Optional
	TimeTilDormantMs *float64 `json:"timeTilDormantMs,omitempty" tf:"time_til_dormant_ms,omitempty"`

	// (Boolean) If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
	// If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
	// +kubebuilder:validation:Optional
	UseClassicParameterFlow *bool `json:"useClassicParameterFlow,omitempty" tf:"use_classic_parameter_flow,omitempty"`

	// (Attributes List) The template versions to manage. At least one version (with active = true) is required when creating a new template, since Coder templates cannot exist without a version. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Versions []VersionsParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type TfVarsInitParameters struct {

	// (String) The name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TfVarsObservation struct {

	// (String) The name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TfVarsParameters struct {

	// (String) The name of the template.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type UsersInitParameters struct {

	// (String) The ID of the template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Role assigned to the user or group. Valid roles are admin and use.
	// Role assigned to the user or group. Valid roles are `admin` and `use`.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type UsersObservation struct {

	// (String) The ID of the template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Role assigned to the user or group. Valid roles are admin and use.
	// Role assigned to the user or group. Valid roles are `admin` and `use`.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type UsersParameters struct {

	// (String) The ID of the template.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Role assigned to the user or group. Valid roles are admin and use.
	// Role assigned to the user or group. Valid roles are `admin` and `use`.
	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role,omitempty"`
}

type VersionsInitParameters struct {

	// (Boolean) Whether this version is the active version of the template. Only one version can be active at a time.
	// Whether this version is the active version of the template. Only one version can be active at a time.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) A path to the directory to create the template version from. Changes in the directory contents will trigger the creation of a new template version.
	// A path to the directory to create the template version from. Changes in the directory contents will trigger the creation of a new template version.
	Directory *string `json:"directory,omitempty" tf:"directory,omitempty"`

	// (String) A message describing the changes in this version of the template. Messages longer than 72 characters will be truncated.
	// A message describing the changes in this version of the template. Messages longer than 72 characters will be truncated.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// (String) The name of the template.
	// The name of the template version. Automatically generated if not provided. If provided, the name *must* change each time the directory contents, or the `tf_vars` attribute are updated.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes Set) Provisioner tags for the template version. (see below for nested schema)
	ProvisionerTags []ProvisionerTagsInitParameters `json:"provisionerTags,omitempty" tf:"provisioner_tags,omitempty"`

	// (see below for nested schema)
	TfVars []TfVarsInitParameters `json:"tfVars,omitempty" tf:"tf_vars,omitempty"`
}

type VersionsObservation struct {

	// (Boolean) Whether this version is the active version of the template. Only one version can be active at a time.
	// Whether this version is the active version of the template. Only one version can be active at a time.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) A path to the directory to create the template version from. Changes in the directory contents will trigger the creation of a new template version.
	// A path to the directory to create the template version from. Changes in the directory contents will trigger the creation of a new template version.
	Directory *string `json:"directory,omitempty" tf:"directory,omitempty"`

	// (String)
	DirectoryHash *string `json:"directoryHash,omitempty" tf:"directory_hash,omitempty"`

	// (String) The ID of the template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) A message describing the changes in this version of the template. Messages longer than 72 characters will be truncated.
	// A message describing the changes in this version of the template. Messages longer than 72 characters will be truncated.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// (String) The name of the template.
	// The name of the template version. Automatically generated if not provided. If provided, the name *must* change each time the directory contents, or the `tf_vars` attribute are updated.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes Set) Provisioner tags for the template version. (see below for nested schema)
	ProvisionerTags []ProvisionerTagsObservation `json:"provisionerTags,omitempty" tf:"provisioner_tags,omitempty"`

	// (see below for nested schema)
	TfVars []TfVarsObservation `json:"tfVars,omitempty" tf:"tf_vars,omitempty"`
}

type VersionsParameters struct {

	// (Boolean) Whether this version is the active version of the template. Only one version can be active at a time.
	// Whether this version is the active version of the template. Only one version can be active at a time.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) A path to the directory to create the template version from. Changes in the directory contents will trigger the creation of a new template version.
	// A path to the directory to create the template version from. Changes in the directory contents will trigger the creation of a new template version.
	// +kubebuilder:validation:Optional
	Directory *string `json:"directory" tf:"directory,omitempty"`

	// (String) A message describing the changes in this version of the template. Messages longer than 72 characters will be truncated.
	// A message describing the changes in this version of the template. Messages longer than 72 characters will be truncated.
	// +kubebuilder:validation:Optional
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// (String) The name of the template.
	// The name of the template version. Automatically generated if not provided. If provided, the name *must* change each time the directory contents, or the `tf_vars` attribute are updated.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes Set) Provisioner tags for the template version. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ProvisionerTags []ProvisionerTagsParameters `json:"provisionerTags,omitempty" tf:"provisioner_tags,omitempty"`

	// (see below for nested schema)
	// +kubebuilder:validation:Optional
	TfVars []TfVarsParameters `json:"tfVars,omitempty" tf:"tf_vars,omitempty"`
}

// TemplateSpec defines the desired state of Template
type TemplateSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TemplateInitParameters `json:"initProvider,omitempty"`
}

// TemplateStatus defines the observed state of Template.
type TemplateStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Template is the Schema for the Templates API. A Coder template. Logs from building template versions can be optionally streamed from the provisioner by setting the TF_LOG environment variable to INFO or higher.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coderd}
type Template struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TemplateSpec   `json:"spec"`
	Status TemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TemplateList contains a list of Templates
type TemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Template `json:"items"`
}

// Repository type metadata.
var (
	Template_Kind             = "Template"
	Template_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Template_Kind}.String()
	Template_KindAPIVersion   = Template_Kind + "." + CRDGroupVersion.String()
	Template_GroupVersionKind = CRDGroupVersion.WithKind(Template_Kind)
)

func init() {
	SchemeBuilder.Register(&Template{}, &TemplateList{})
}
