apiVersion: deployment.coderd.m.crossplane.io/v1alpha1
kind: OAuth2ProviderSettings
metadata:
  annotations:
    meta.upbound.io/example-id: deployment/v1alpha1/oauth2providersettings
  labels:
    testing.upbound.io/example-name: dcr
  name: dcr
  namespace: crossplane-system
spec:
  forProvider:
    dynamicClientRegistrationEnabled: true
